MODULE FIELD_STAT_MODULE

USE PARKIND1, ONLY : JPIB

IMPLICIT NONE

TYPE FIELD_STAT
  INTEGER (KIND=JPIB) :: MEMORY_HOST_CUR = 0
  INTEGER (KIND=JPIB) :: MEMORY_HOST_MAX = 0

  INTEGER (KIND=JPIB) :: MEMORY_DEVICE_CUR = 0
  INTEGER (KIND=JPIB) :: MEMORY_DEVICE_MAX = 0

  INTEGER (KIND=JPIB) :: NFIELDS_CUR = 0
  INTEGER (KIND=JPIB) :: NFIELDS_MAX = 0
END TYPE

LOGICAL, SAVE :: FIELD_STAT_ENABLE = .FALSE.

TYPE (FIELD_STAT), SAVE :: FIELD_STATISTICS

END MODULE
