!Copyright 2023 Meteo-France, ECMWF 
!
!Licensed under the Apache License, Version 2.0 (the "License");
!you may not use this file except in compliance with the License.
!You may obtain a copy of the License at
!
!    http://www.apache.org/licenses/LICENSE-2.0
!
!    Unless required by applicable law or agreed to in writing, software
!    distributed under the License is distributed on an "AS IS" BASIS,
!    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!    See the License for the specific language governing permissions and
!    limitations under the License.

MODULE FIELD_BASIC_MODULE

USE DEV_ALLOC_MODULE
USE PARKIND1, ONLY : JPIM

IMPLICIT NONE

PRIVATE

TYPE GPU_STATS
  INTEGER :: TRANSFER_CPU_TO_GPU = 0
  INTEGER :: TRANSFER_GPU_TO_CPU = 0
  REAL :: TOTAL_TIME_TRANSFER_CPU_TO_GPU = 0
  REAL :: TOTAL_TIME_TRANSFER_GPU_TO_CPU = 0
  CONTAINS
  PROCEDURE :: INC_CPU_TO_GPU_TRANSFER
  PROCEDURE :: INC_GPU_TO_CPU_TRANSFER
END TYPE GPU_STATS

TYPE, ABSTRACT :: FIELD_BASIC
  LOGICAL :: THREAD_BUFFER = .FALSE.

  INTEGER(KIND=JPIM) :: ISTATUS = 0
  INTEGER(KIND=JPIM) :: LAST_CONTIGUOUS_DIMENSION = 0

  TYPE(GPU_STATS) :: STATS

  LOGICAL :: LOBJECT_COPIED = .FALSE.

CONTAINS
  PROCEDURE (FIELD_BASIC_SYNC), DEFERRED :: SYNC_HOST_RDWR
  PROCEDURE (FIELD_BASIC_SYNC), DEFERRED :: SYNC_HOST_RDONLY
  PROCEDURE (FIELD_BASIC_SYNC), DEFERRED :: SYNC_DEVICE_RDWR
  PROCEDURE (FIELD_BASIC_SYNC), DEFERRED :: SYNC_DEVICE_RDONLY
END TYPE FIELD_BASIC

PUBLIC :: FIELD_BASIC

ABSTRACT INTERFACE
  SUBROUTINE FIELD_BASIC_SYNC (SELF, QUEUE)
    IMPORT FIELD_BASIC
    CLASS(FIELD_BASIC), INTENT(INOUT) :: SELF
    INTEGER, OPTIONAL,  INTENT(IN)    :: QUEUE
  END SUBROUTINE
END INTERFACE

PUBLIC :: FIELD_BASIC_SYNC

CONTAINS

SUBROUTINE INC_CPU_TO_GPU_TRANSFER(SELF, START, FINISH)
  CLASS(GPU_STATS), INTENT(INOUT) :: SELF
  REAL, INTENT(IN) :: START, FINISH
  SELF%TRANSFER_CPU_TO_GPU = SELF%TRANSFER_CPU_TO_GPU + 1
  SELF%TOTAL_TIME_TRANSFER_CPU_TO_GPU = SELF%TOTAL_TIME_TRANSFER_CPU_TO_GPU + FINISH - START
END SUBROUTINE

SUBROUTINE INC_GPU_TO_CPU_TRANSFER(SELF, START, FINISH)
  CLASS(GPU_STATS), INTENT(INOUT) :: SELF
  REAL, INTENT(IN) :: START, FINISH
  SELF%TRANSFER_GPU_TO_CPU = SELF%TRANSFER_GPU_TO_CPU + 1
  SELF%TOTAL_TIME_TRANSFER_GPU_TO_CPU = SELF%TOTAL_TIME_TRANSFER_GPU_TO_CPU + FINISH - START
END SUBROUTINE

END MODULE FIELD_BASIC_MODULE
