MODULE FIELD_BASIC_MODULE

USE OMP_LIB, ONLY: OMP_GET_MAX_THREADS, OMP_GET_THREAD_NUM
USE IEEE_ARITHMETIC, ONLY: IEEE_SIGNALING_NAN
USE DEV_ALLOC_MODULE
USE PARKIND1, ONLY : JPIM

IMPLICIT NONE

PRIVATE

TYPE GPU_STATS
  INTEGER :: TRANSFER_CPU_TO_GPU = 0
  INTEGER :: TRANSFER_GPU_TO_CPU = 0
  REAL :: TOTAL_TIME_TRANSFER_CPU_TO_GPU = 0
  REAL :: TOTAL_TIME_TRANSFER_GPU_TO_CPU = 0
  CONTAINS
  PROCEDURE :: INC_CPU_TO_GPU_TRANSFER
  PROCEDURE :: INC_GPU_TO_CPU_TRANSFER
END TYPE GPU_STATS

TYPE, ABSTRACT :: FIELD_BASIC
  LOGICAL :: THREAD_BUFFER = .FALSE.

  INTEGER(KIND=JPIM) :: ISTATUS = 0
  INTEGER(KIND=JPIM) :: LAST_CONTIGUOUS_DIMENSION = 0

  TYPE(GPU_STATS) :: STATS

  LOGICAL :: LOBJECT_COPIED = .FALSE.

CONTAINS
  PROCEDURE (FIELD_BASIC_SYNC), DEFERRED :: SYNC_HOST_RDWR
  PROCEDURE (FIELD_BASIC_SYNC), DEFERRED :: SYNC_HOST_RDONLY
  PROCEDURE (FIELD_BASIC_SYNC), DEFERRED :: SYNC_DEVICE_RDWR
  PROCEDURE (FIELD_BASIC_SYNC), DEFERRED :: SYNC_DEVICE_RDONLY
END TYPE FIELD_BASIC

PUBLIC :: FIELD_BASIC

ABSTRACT INTERFACE
  SUBROUTINE FIELD_BASIC_SYNC (SELF, QUEUE)
    IMPORT FIELD_BASIC
    CLASS(FIELD_BASIC), INTENT(INOUT) :: SELF
    INTEGER, OPTIONAL,  INTENT(IN)    :: QUEUE
  END SUBROUTINE
END INTERFACE

PUBLIC :: FIELD_BASIC_SYNC

END MODULE FIELD_BASIC_MODULE
