MODULE FIELD_DEFAULTS_MODULE
  USE PARKIND1
  LOGICAL :: USE_INIT_DEBUG_VALUE = .FALSE.
  REAL(KIND=JPRM) :: INIT_DEBUG_VALUE_JPRM = 0.0_JPRM
  REAL(KIND=JPRB) :: INIT_DEBUG_VALUE_JPRB = 0.0_JPRB
  REAL(KIND=JPRD) :: INIT_DEBUG_VALUE_JPRD = 0.0_JPRD
  INTEGER(KIND=JPIM) :: INIT_DEBUG_VALUE_JPIM = 0_JPIM
  LOGICAL(KIND=JPLM) :: INIT_DEBUG_VALUE_JPLM = .FALSE.
  LOGICAL :: GET_DEBUG_PRINT_CRC = .FALSE.
  LOGICAL :: GET_DEBUG_PRINT_LOCATION = .FALSE.
  LOGICAL :: INIT_PINNED_VALUE = .FALSE.
  LOGICAL :: INIT_SYNC_ON_FINAL = .TRUE.
  LOGICAL :: INIT_INITIALIZED = .TRUE.
  LOGICAL :: INIT_MAP_DEVPTR = .TRUE.
  INTEGER :: GET_DEBUG_PRINT_LOCATION_DEPTH = 3

! WHEN CREATING A FIELD OWNER, IF THE DELAYED VALUE IS NOT SPECIFIED
! THEN IT WILL BE THE VALUE SPECIFIED BY DELAYED_DEFAULT_VALUE
  LOGICAL :: DELAYED_DEFAULT_VALUE = .TRUE.

  NAMELIST / NAMFIELD_API / &
   & USE_INIT_DEBUG_VALUE,  INIT_DEBUG_VALUE_JPRM,        &
   & INIT_DEBUG_VALUE_JPRB, INIT_DEBUG_VALUE_JPRD,        &
   & INIT_DEBUG_VALUE_JPIM, INIT_DEBUG_VALUE_JPLM,        &
   & GET_DEBUG_PRINT_CRC,   GET_DEBUG_PRINT_LOCATION,     &
   & INIT_PINNED_VALUE,     INIT_SYNC_ON_FINAL,           &
   & INIT_MAP_DEVPTR,       GET_DEBUG_PRINT_LOCATION_DEPTH

END MODULE FIELD_DEFAULTS_MODULE
