MODULE FIELD_STATISTICS_MODULE

USE PARKIND1, ONLY : JPIB

IMPLICIT NONE

TYPE FIELD_STATISTICS_TYPE
  INTEGER (KIND=JPIB) :: MEMORY_HOST_CUR = 0
  INTEGER (KIND=JPIB) :: MEMORY_HOST_MAX = 0

  INTEGER (KIND=JPIB) :: MEMORY_DEVICE_CUR = 0
  INTEGER (KIND=JPIB) :: MEMORY_DEVICE_MAX = 0

  INTEGER (KIND=JPIB) :: NFIELDS_CUR = 0
  INTEGER (KIND=JPIB) :: NFIELDS_MAX = 0
END TYPE

PRIVATE

LOGICAL, SAVE :: FIELD_STATISTICS_ENABLE = .FALSE.
TYPE (FIELD_STATISTICS_TYPE), SAVE :: FIELD_STATISTICS

PUBLIC :: FIELD_STATISTICS, FIELD_STATISTICS_ENABLE

END MODULE
