
USE FIELD_STATISTICS_MODULE, ONLY : FS => FIELD_STATISTICS, FE => FIELD_STATISTICS_ENABLE

#define field_statistics_new() IF(FE)THEN;FS%NFIELDS_CUR=FS%NFIELDS_CUR+1;FS%NFIELDS_MAX=MAX(FS%NFIELDS_CUR,FS%NFIELDS_MAX);ENDIF
#define field_statistics_delete() IF(FE)THEN;FS%NFIELDS_CUR=FS%NFIELDS_CUR-1;ENDIF

#define field_statistics_host_allocate(p) IF(FE)THEN;FS%MEMORY_HOST_CUR=FS%MEMORY_HOST_CUR+SIZE(p)*KIND(p);FS%MEMORY_HOST_MAX=MAX(FS%MEMORY_HOST_CUR,FS%MEMORY_HOST_MAX);ENDIF
#define field_statistics_host_deallocate(p) IF(FE)THEN;FS%MEMORY_HOST_CUR=FS%MEMORY_HOST_CUR-SIZE(p)*KIND(p);ENDIF

#define field_statistics_device_allocate(p) IF(FE)THEN;FS%MEMORY_DEVICE_CUR=FS%MEMORY_DEVICE_CUR+SIZE(p)*KIND(p);FS%MEMORY_DEVICE_MAX=MAX(FS%MEMORY_DEVICE_CUR,FS%MEMORY_DEVICE_MAX);ENDIF
#define field_statistics_device_deallocate(p) IF(FE)THEN;FS%MEMORY_DEVICE_CUR=FS%MEMORY_DEVICE_CUR-SIZE(p)*KIND(p);ENDIF


