MODULE FIELD_DEFAULTS_MODULE
  USE PARKIND1
  LOGICAL :: USE_INIT_DEBUG_VALUE = .FALSE.
  REAL(KIND=JPRM) :: INIT_DEBUG_VALUE_JPRM = 0.0_JPRM
  REAL(KIND=JPRB) :: INIT_DEBUG_VALUE_JPRB = 0.0_JPRB
  REAL(KIND=JPRD) :: INIT_DEBUG_VALUE_JPRD = 0.0_JPRD
  INTEGER(KIND=JPIM) :: INIT_DEBUG_VALUE_JPIM = 0_JPIM
  LOGICAL(KIND=JPLM) :: INIT_DEBUG_VALUE_JPLM = .FALSE.
  LOGICAL(KIND=JPLM) :: GET_DEBUG_PRINT_CRC = .FALSE.
  LOGICAL(KIND=JPLM) :: GET_DEBUG_PRINT_LOCATION = .FALSE.
  LOGICAL :: INIT_PINNED_VALUE = .FALSE.
  LOGICAL :: INIT_SYNC_ON_FINAL = .TRUE.
  LOGICAL :: INIT_MAP_DEVPTR = .TRUE.
END MODULE FIELD_DEFAULTS_MODULE
