USE FIELD_MODULE
USE FIELD_HELPER_MODULE

INTEGER (KIND=JPIM) :: NFLEVG, NPROMA, NGPBLKS
REAL (KIND=JPRB), ALLOCATABLE :: ZDATA (:,:,:)
TYPE (FIELD_3D), POINTER :: YLF3

REAL (KIND=JPRB), POINTER  :: Z (:,:,:)


NFLEVG =  9
NPROMA = 16
NGPBLKS = 4

ALLOCATE (ZDATA (NPROMA, NFLEVG, NGPBLKS))

DO JBLK = 1, NGPBLKS
  DO JLEV = 1, NFLEVG
    DO JLON = 1, NPROMA
      ZDATA (JLON, JLEV, JBLK) = JLON + NPROMA * (JBLK - 1) + JLEV * 100
    ENDDO
  ENDDO
ENDDO

ALLOCATE (YLF3)
YLF3 = FIELD_3D (DATA=ZDATA, PERSISTENT=.TRUE.)


Z => GET_DEVICE_DATA_RDONLY (YLF3)

PRINT *, Z (:,1,1)

CALL YLF3%FINAL


END
