USE FIELD_MODULE
USE FIELD_HELPER_MODULE

INTEGER (KIND=JPIM) :: NFLEVG, NPROMA, NGPBLKS

REAL (KIND=JPRB), ALLOCATABLE :: ZDATA3 (:,:,:)
TYPE (FIELD_3D), POINTER :: YLF3

REAL (KIND=JPRB), POINTER  :: Z (:,:,:)


NFLEVG =  9
NPROMA = 16
NGPBLKS = 4

ALLOCATE (ZDATA3 (NPROMA, NFLEVG, NGPBLKS))

DO JBLK = 1, NGPBLKS
  DO JLEV = 1, NFLEVG
    DO JLON = 1, NPROMA
      ZDATA3 (JLON, JLEV, JBLK) = JLON + NPROMA * (JBLK - 1) + JLEV * 100
    ENDDO
  ENDDO
ENDDO

ALLOCATE (YLF3)
!YLF3 = FIELD_3D (DATA=ZDATA3 (:,1:3,:), PERSISTENT=.TRUE.)
YLF3 = FIELD_3D (DATA=ZDATA3 (:,1:3,:), PERSISTENT=.TRUE.)


PRINT *, '-----------  HOST/HOST  -----------'

Z => GET_HOST_DATA_RDONLY (YLF3)

DO JLON = 1, NPROMA
  PRINT *, JLON, Z (JLON,1,1)
ENDDO

PRINT *, '-----------  DEVICE/HOST  -----------'

Z => GET_DEVICE_DATA_RDONLY (YLF3)

DO JLON = 1, NPROMA
  PRINT *, JLON, Z (JLON,1,1)
ENDDO

PRINT *, '----------- DEVICE/DEVICE -----------'

!$acc serial present (Z)
DO JLON = 1, NPROMA
  PRINT *, JLON, Z (JLON,1,1)
ENDDO
!$acc end serial

CALL YLF3%FINAL


END
