!COPYRIGHT Meteo-France 2023
PROGRAM FINAL_WRAPPER_GPU
        ! TEST IF DESTROYING THE DATA ON GPU WORKS

        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        IMPLICIT NONE
        CLASS(FIELD_2RB), POINTER :: W => NULL()
        REAL(KIND=JPRB), ALLOCATABLE :: D(:,:)
        REAL(KIND=JPRB), POINTER :: D_GPU(:,:)

        ALLOCATE(D(10,10))
        D=7

        CALL FIELD_NEW(W, DATA=D)
        CALL W%GET_DEVICE_DATA_RDONLY(D_GPU)

        IF (.NOT. ASSOCIATED(W%DEVPTR)) THEN
                ERROR STOP
        END IF

        CALL W%DELETE_DEVICE()

        IF (ASSOCIATED(W%DEVPTR)) THEN
                ERROR STOP
        END IF
        CALL FIELD_DELETE(W)
END PROGRAM FINAL_WRAPPER_GPU
