PROGRAM INIT
        ! TEST IF DESTROYING THE DATA ON GPU WORKS

        USE FIELD_MODULE
        IMPLICIT NONE
        TYPE(FIELD_2D_WRAPPER) :: W
        REAL(KIND=JPRB), ALLOCATABLE :: D(:,:)
        REAL(KIND=JPRB), POINTER :: D_GPU(:,:)

        ALLOCATE(D(10,10))
        D=7

        CALL W%INIT(D)
        CALL W%MOVE_DATA_TO_DEVICE_RDONLY(D_GPU)

        IF (.NOT. ASSOCIATED(W%DEVPTR)) THEN
                ERROR STOP
        END IF

        CALL W%DELETE_DEVICE()

        IF (ASSOCIATED(W%DEVPTR)) THEN
                ERROR STOP
        END IF
END PROGRAM INIT
