PROGRAM FINAL_OWNER
        ! TEST IF OWNER IS DESTROYED WHEN CALLING FINAL

        USE FIELD_MODULE
        IMPLICIT NONE
        TYPE(FIELD_2RB_OWNER) :: O
        REAL(KIND=JPRB), POINTER :: PTR(:,:)

        CALL O%INIT([10,1],[21,11])
        CALL O%GET_HOST_DATA_RDWR(PTR)
        PTR=42
        CALL O%FINAL()

        IF (ASSOCIATED(O%PTR)) THEN
                ERROR STOP
        END IF
        IF (ASSOCIATED(O%DEVPTR)) THEN
                ERROR STOP
        END IF
END PROGRAM FINAL_OWNER
