PROGRAM GATHER_SCATTER_COLLAPSE1

USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FIELD_GATHSCAT_COLLAPSE1_MODULE
USE PARKIND1
USE FIELD_ABORT_MODULE

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NPROMA = 10, NGPBLKS = 4, NFLEVG = 10, NGPTOT = NPROMA * NGPBLKS - 4
INTEGER (KIND=JPIM), PARAMETER :: NMISS = -99999, NNEW = 22222

TYPE (FIELD_GATHSCAT_COLLAPSE1) :: YL_FGS

LOGICAL :: LLTRIG (NPROMA, NGPBLKS)
CLASS (FIELD_2LM), POINTER :: YLTRIG => NULL ()

INTEGER (KIND=JPIM), ALLOCATABLE :: ID (:,:,:)
CLASS (FIELD_3IM), POINTER :: YLFD => NULL()

INTEGER (KIND=JPIM),POINTER :: ID_FILTERED (:,:,:) => NULL ()

INTEGER (KIND=JPIM) :: JLON, JBLK, JLEV, IIDIA, IFDIA

INTEGER (KIND=JPIM) :: FUNC

FUNC (JLON, JLEV, JBLK) = (JBLK-1) * NPROMA + (JLON-1) + NGPTOT * (JLEV-1)


LLTRIG=.FALSE.

DO JBLK = 1, NGPBLKS
  IIDIA = 1 
  IFDIA = MERGE (NPROMA, NGPTOT - (JBLK - 1) * NPROMA, JBLK < NGPBLKS)
  DO JLON = IIDIA, IFDIA
    LLTRIG (JLON, JBLK) = MOD (JLON, 2) == 0
  ENDDO
ENDDO

CALL FIELD_NEW (YLTRIG, DATA=LLTRIG)

ALLOCATE(ID (NPROMA, NFLEVG, NGPBLKS))

DO JBLK = 1, NGPBLKS
  IIDIA = 1
  IFDIA = MERGE (NPROMA, NGPTOT - (JBLK - 1) * NPROMA, JBLK < NGPBLKS)
  DO JLEV = 1, NFLEVG
    DO JLON = IIDIA, IFDIA
      ID (JLON, JLEV, JBLK) = FUNC (JLON, JLEV, JBLK)
    ENDDO
    DO JLON = IFDIA+1, NPROMA
      ID (JLON, JLEV, JBLK) = NMISS
    ENDDO
  ENDDO
ENDDO

CALL FIELD_NEW (YLFD, DATA=ID)

CALL YL_FGS%INIT (YLTRIG, NGPTOT)
ID_FILTERED => GATHER_HOST_DATA_RDWR (YL_FGS, YLFD)

DO JBLK = 1, YL_FGS%KGPBLKS
  IIDIA = 1
  IFDIA = MERGE (YL_FGS%KLON, YL_FGS%KGPTOT - (JBLK - 1) * YL_FGS%KLON, JBLK < YL_FGS%KGPBLKS)
  DO JLEV = 1, NFLEVG
    DO JLON = IIDIA, IFDIA
      ID_FILTERED (JLON, JLEV, JBLK) = NNEW
    ENDDO
    DO JLON = IFDIA+1, YL_FGS%KLON
      ID_FILTERED (JLON, JLEV, JBLK) = NMISS
    ENDDO
  ENDDO
ENDDO

CALL YL_FGS%SCATTER ()

DO JBLK = 1, NGPBLKS
  IIDIA = 1 
  IFDIA = MERGE (NPROMA, NGPTOT - (JBLK - 1) * NPROMA, JBLK < NGPBLKS)

  DO JLEV = 1, NFLEVG

    DO JLON = IIDIA, IFDIA
      IF (LLTRIG (JLON, JBLK)) THEN
        IF (ID (JLON, JLEV, JBLK) /= NNEW) &
          & CALL FIELD_ABORT ("ERROR")
      ELSE
        IF (ID (JLON, JLEV, JBLK) /= FUNC (JLON, JLEV, JBLK)) &
          & CALL FIELD_ABORT ("ERROR")
      ENDIF
    ENDDO

    DO JLON = IFDIA+1, NPROMA
      IF (ID (JLON, JLEV, JBLK) /= NMISS) &
        & CALL FIELD_ABORT ("ERROR")
    ENDDO
    
  ENDDO

ENDDO

CALL FIELD_DELETE (YLTRIG)

END PROGRAM
