PROGRAM GATHER_SCATTER_COLLAPSE2

USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FIELD_GATHSCAT_COLLAPSE2_MODULE
USE PARKIND1
USE FIELD_ABORT_MODULE

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NPROMA = 10, NGPBLKS = 4, NFLEVG = 10, NFLD = 5, NGPTOT = NPROMA * NGPBLKS - 4
INTEGER (KIND=JPIM), PARAMETER :: NMISS = -99999, NNEW = 22222

TYPE (FIELD_GATHSCAT_COLLAPSE2) :: YL_FGS

LOGICAL :: LLTRIG (NPROMA, NFLEVG, NGPBLKS)
CLASS (FIELD_3LM), POINTER :: YLTRIG => NULL ()

INTEGER (KIND=JPIM), ALLOCATABLE :: ID (:,:,:,:)
CLASS (FIELD_4IM), POINTER :: YLFD => NULL()

INTEGER (KIND=JPIM),POINTER :: ID_FILTERED (:,:,:) => NULL ()

INTEGER (KIND=JPIM) :: JLON, JBLK, JLEV, JFLD, IIDIA, IFDIA

INTEGER (KIND=JPIM) :: FUNC

FUNC (JLON, JLEV, JFLD, JBLK) = (JBLK-1) * NPROMA + (JLON-1) + NGPTOT * (JLEV-1 + NFLEVG * (JFLD-1))


LLTRIG=.FALSE.

DO JBLK = 1, NGPBLKS
  IIDIA = 1 
  IFDIA = MERGE (NPROMA, NGPTOT - (JBLK - 1) * NPROMA, JBLK < NGPBLKS)
  DO JLEV = 1, NFLEVG
     DO JLON = IIDIA, IFDIA
       LLTRIG (JLON,JLEV,JBLK) = MOD (JLON+JLEV, 2) == 0
     ENDDO
  ENDDO
ENDDO

CALL FIELD_NEW (YLTRIG, DATA=LLTRIG)

ALLOCATE(ID (NPROMA, NFLEVG, NFLD, NGPBLKS))

DO JBLK = 1, NGPBLKS
  IIDIA = 1
  IFDIA = MERGE (NPROMA, NGPTOT - (JBLK - 1) * NPROMA, JBLK < NGPBLKS)
  DO JFLD = 1, NFLD
    DO JLEV = 1, NFLEVG
      DO JLON = IIDIA, IFDIA
        ID (JLON, JLEV, JFLD, JBLK) = FUNC (JLON, JLEV, JFLD, JBLK)
      ENDDO
      DO JLON = IFDIA+1, NPROMA
        ID (JLON, JLEV, JFLD, JBLK) = NMISS
      ENDDO
    ENDDO
  ENDDO
ENDDO

CALL FIELD_NEW (YLFD, DATA=ID)

CALL YL_FGS%INIT (YLTRIG, NGPTOT)
ID_FILTERED => GATHER_HOST_DATA_RDWR (YL_FGS, YLFD)

DO JBLK = 1, YL_FGS%KGPBLKS
  IIDIA = 1
  IFDIA = MERGE (YL_FGS%KLON, YL_FGS%KGPTOT - (JBLK - 1) * YL_FGS%KLON, JBLK < YL_FGS%KGPBLKS)
  DO JFLD = 1, NFLD
    DO JLON = IIDIA, IFDIA
      ID_FILTERED (JLON, JFLD, JBLK) = NNEW
    ENDDO
    DO JLON = IFDIA+1, YL_FGS%KLON
      ID_FILTERED (JLON, JFLD, JBLK) = NMISS
    ENDDO
  ENDDO
ENDDO

CALL YL_FGS%SCATTER ()

DO JBLK = 1, NGPBLKS
  IIDIA = 1 
  IFDIA = MERGE (NPROMA, NGPTOT - (JBLK - 1) * NPROMA, JBLK < NGPBLKS)

  DO JFLD = 1, NFLD
    DO JLEV = 1, NFLEVG

      DO JLON = IIDIA, IFDIA
        IF (LLTRIG (JLON, JLEV, JBLK)) THEN
          IF (ID (JLON, JLEV, JFLD, JBLK) /= NNEW) &
            & CALL FIELD_ABORT ("ERROR")
        ELSE
          IF (ID (JLON, JLEV, JFLD, JBLK) /= FUNC (JLON, JLEV, JFLD, JBLK)) &
            & CALL FIELD_ABORT ("ERROR")
        ENDIF
      ENDDO

      DO JLON = IFDIA+1, NPROMA
        IF (ID (JLON, JLEV, JFLD, JBLK) /= NMISS) &
          & CALL FIELD_ABORT ("ERROR")
      ENDDO
      
    ENDDO
  ENDDO

ENDDO

CALL FIELD_DELETE (YLTRIG)

END PROGRAM
