PROGRAM GATHER_SCATTER_COLLAPSE2

USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FIELD_GATHSCAT_COLLAPSE2_MODULE
USE PARKIND1
USE FIELD_ABORT_MODULE
IMPLICIT NONE

TYPE(FIELD_GATHSCAT_COLLAPSE2):: FGS
CLASS(FIELD_3LM), POINTER :: FTRIG => NULL()
INTEGER, PARAMETER :: NPROMA = 10, NGPBLKS = 4, NFLEVG = 10, NFLD = 5
LOGICAL :: TRIG(NPROMA,NFLEVG,NGPBLKS)
INTEGER ::JLON,JBLK,JLEV,JFLD,IIDIA, IFDIA
INTEGER :: NGPTOT 

INTEGER(KIND=JPIM), ALLOCATABLE :: D(:,:,:,:)
CLASS(FIELD_4IM),POINTER :: FD => NULL()
INTEGER(KIND=JPIM),POINTER :: FILTERED_D(:,:,:) => NULL()

INTEGER :: FUNC
INTEGER, PARAMETER :: IMISS = -99999

FUNC (JLON, JLEV, JFLD, JBLK) = (JBLK-1) * NPROMA + (JLON-1) + NGPTOT * (JLEV-1 + NFLEVG * (JFLD-1))

NGPTOT = NPROMA * NGPBLKS - 4

TRIG=.FALSE.

DO JBLK = 1, NGPBLKS
  IIDIA = 1 
  IFDIA = MERGE (NPROMA, NGPTOT - (JBLK - 1) * NPROMA, JBLK < NGPBLKS)
  DO JLEV = 1, NFLEVG
     DO JLON=1,NPROMA
       TRIG(JLON,JLEV,JBLK) = MOD (JLON+JLEV, 2) == 0
     ENDDO
  ENDDO
ENDDO

CALL FIELD_NEW (FTRIG, DATA=TRIG)

ALLOCATE(D (NPROMA, NFLEVG, NFLD, NGPBLKS))

DO JBLK = 1, NGPBLKS
  IIDIA = 1
  IFDIA = MERGE (NPROMA, NGPTOT - (JBLK - 1) * NPROMA, JBLK < NGPBLKS)
  DO JFLD = 1, NFLD
    DO JLEV = 1, NFLEVG
      DO JLON = IIDIA, IFDIA
        D (JLON, JLEV, JFLD, JBLK) = 1
      ENDDO
      DO JLON = IFDIA+1, NPROMA
        D (JLON, JLEV, JFLD, JBLK) = IMISS
      ENDDO
    ENDDO
  ENDDO
ENDDO

CALL FIELD_NEW (FD, DATA=D)

CALL FGS%INIT (FTRIG, NGPTOT)
FILTERED_D => GATHER_HOST_DATA_RDWR (FGS, FD)

DO JBLK = 1, FGS%KGPBLKS
  IIDIA = 1
  IFDIA = MERGE (FGS%KLON, FGS%KGPTOT - (JBLK - 1) * FGS%KLON, JBLK < FGS%KGPBLKS)
  DO JFLD = 1, NFLD
    DO JLON = IIDIA, IFDIA
      FILTERED_D (JLON, JFLD, JBLK) = 2
    ENDDO
    DO JLON = IFDIA+1, FGS%KLON
      FILTERED_D (JLON, JFLD, JBLK) = IMISS
    ENDDO
  ENDDO
ENDDO

CALL FGS%SCATTER ()

DO JBLK = 1, NGPBLKS
  IIDIA = 1 
  IFDIA = MERGE (NPROMA, NGPTOT - (JBLK - 1) * NPROMA, JBLK < NGPBLKS)

  DO JFLD = 1, NFLD
    DO JLEV = 1, NFLEVG

      DO JLON = IIDIA, IFDIA
        IF (MOD (JLON+JLEV, 2) == 0) THEN
          IF (D (JLON, JLEV, JFLD, JBLK) /= 2) CALL FIELD_ABORT ("ERROR")
        ELSE
          IF (D (JLON, JLEV, JFLD, JBLK) /= 1) CALL FIELD_ABORT ("ERROR")
        ENDIF
      ENDDO

      DO JLON = IFDIA+1, NPROMA
        IF (D (JLON, JLEV, JFLD, JBLK) /= IMISS) CALL FIELD_ABORT ("ERROR")
      ENDDO
      
    ENDDO
  ENDDO

ENDDO

CALL FIELD_DELETE(FTRIG)

END PROGRAM
