PROGRAM GET_STATS_NO_OPENACC
#ifndef _OPENACC
        ! TEST IF STATS ARE CORRECTLY COMPUTED WHEN OPENACC IS DESACTIVATED
        USE FIELD_MODULE
        IMPLICIT NONE
        TYPE(FIELD_2D_WRAPPER) :: W
        REAL(KIND=JPRB), ALLOCATABLE :: D(:,:)
        REAL(KIND=JPRB), POINTER :: D_GPU(:,:)
        REAL(KIND=JPRB), POINTER :: D_CPU(:,:)

        ALLOCATE(D(10,10))

        CALL W%INIT(D)
        CALL W%MOVE_DATA_TO_DEVICE_RDONLY(D_GPU)
        CALL W%MOVE_DATA_TO_DEVICE_RDONLY(D_GPU)
        ! SHOULD BE 0 BECAUSE THE DATA HAVE NOT MOVED SINCE OPENACC IS DESACTIVATED
        IF (W%STATS%TRANSFER_CPU_TO_GPU /= 0) THEN
                ERROR STOP
        END IF
        IF (W%STATS%TOTAL_TIME_TRANSFER_CPU_TO_GPU /= 0) THEN
                ERROR STOP
        END IF

        IF (.NOT. ASSOCIATED(W%PTR, W%DEVPTR)) THEN
                ERROR STOP
        END IF

        CALL W%FINAL
#endif _OPENACC
END PROGRAM GET_STATS_NO_OPENACC
