!COPYRIGHT Meteo-France 2023
PROGRAM GET_VIEW_WHEN_UNINITIALIZED
        !CHECK THAT IT IS POSSIBLE TO USE GET_VIEW WHEN THE DATA ARE
        !UNINITIALIZED

        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        USE OML_MOD
        IMPLICIT NONE

        CLASS(FIELD_2IM), POINTER :: O => NULL()
        INTEGER, PARAMETER :: NPROMA = 24
        INTEGER :: IBLK,JLON
        INTEGER(KIND=JPIM), POINTER :: VIEW(:) => NULL()
        INTEGER(KIND=JPIM), POINTER :: PTR(:,:) => NULL()

        CALL FIELD_NEW(O, LBOUNDS=[1,1], UBOUNDS=[NPROMA,1])

        !$OMP PARALLEL PRIVATE(VIEW, JLON) 
        !$OMP DO
        DO IBLK=1,OML_MAX_THREADS()
          VIEW => O%GET_VIEW(IBLK)
          DO JLON = 1, NPROMA
            VIEW(JLON) = 7
          ENDDO
        END DO
        !$OMP END DO
        !$OMP END PARALLEL

        CALL O%GET_HOST_DATA_RDONLY(PTR)
        IF (.NOT. ALL(PTR==7))THEN
                ERROR STOP
        ENDIF

        CALL FIELD_DELETE(O)
END PROGRAM GET_VIEW_WHEN_UNINITIALIZED
