!COPYRIGHT Meteo-France 2023
PROGRAM GET_VIEW_WHEN_UNALLOCATED
        !CHECK THAT IT IS NOT POSSIBLE TO USE GET_VIEW WHEN THE DATA ARE
        !UNALLOCATED

        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        USE OML_MOD
        IMPLICIT NONE

        CLASS(FIELD_2IM), POINTER :: O => NULL()
        INTEGER, PARAMETER :: NPROMA = 24
        INTEGER :: IBLK,JLON
        INTEGER(KIND=JPIM), POINTER :: VIEW(:) => NULL()

        CALL FIELD_NEW(O, LBOUNDS=[1,1], UBOUNDS=[NPROMA,1], DELAYED=.TRUE.)

        !$OMP PARALLEL PRIVATE(VIEW, JLON) 
        !$OMP DO
        DO IBLK=1,OML_MAX_THREADS()
        !SHOULD CRASH
          VIEW => O%GET_VIEW(IBLK)
          DO JLON = 1, NPROMA
            VIEW(JLON) = 7
          ENDDO
        END DO
        !$OMP END DO
        !$OMP END PARALLEL

        !SHOULD NEVER REACH THAT PART OF THE PROGRAM
        CALL FIELD_DELETE(O)

END PROGRAM GET_VIEW_WHEN_UNALLOCATED
