PROGRAM INIT
  ! GET_VIEW USED TO NOT CHECK FOR NULL POINTER BEFORE SETTING THE DATA TO ZERO
  ! THIS TEST_CASE ENSURE THE BUG DOE NOT COME BACK
 
  USE FIELD_MODULE
  IMPLICIT NONE
  TYPE(FIELD_2D_WRAPPER) :: W
  REAL(KIND=JPRB), ALLOCATABLE :: D(:,:)
  REAL(KIND=JPRB), POINTER :: D_CPU(:,:)

  ALLOCATE(D(10,10))
  D=7

  CALL W%INIT(D)
  D=42
  W%ACTIVE=.FALSE.
  !EVEN IF WE ASKED TO SET THE DATA TO ZERO,
  !IT SHOULD NOT HAPPEN BECAUSE WE SET ACTIVE TO FALSE
  CALL W%GET_VIEW(D_CPU,1,.TRUE.)

  IF (ALL(W%PTR == 42)) THEN
    STOP
  ELSE
    ERROR STOP
  END IF 
END PROGRAM INIT
