PROGRAM INIT_WRAPPER_LBOUNDS
        ! TEST IF WRAPPER IS USING THE ORIGINAL LBOUNDS
        USE FIELD_MODULE
        IMPLICIT NONE
        TYPE(FIELD_2RB_WRAPPER) :: W
        REAL(KIND=JPRB), ALLOCATABLE :: D(:,:,:)
        INTEGER :: LBOUNDS(2)

        ALLOCATE(D(0:10, 5:10, 100:200))
        CALL W%INIT(D(:,7,:), LBOUNDS=[0, 100])
        LBOUNDS = LBOUND(W%PTR)

        IF (LBOUNDS(1) /= 0 .OR. LBOUNDS(2) /= 100) THEN
                ERROR STOP
        END IF 
END PROGRAM INIT_WRAPPER_LBOUNDS
