PROGRAM INIT_WRAPPER
        ! TEST IF WRAPPER IS REALLY WRAPPING DATA
        ! IF IT IS WRAPPING THEN MODIFYING THE WRAPED DATA SHOULD BE SEEN IN
        ! WRAPPER TOO

        USE FIELD_MODULE
        IMPLICIT NONE
        TYPE(FIELD_2RB_WRAPPER) :: W
        REAL(KIND=JPRB), ALLOCATABLE :: D(:,:)

        ALLOCATE(D(10,10))
        D=7

        CALL W%INIT(D)
        D=42

        IF (.NOT. ALL(W%PTR == 42)) THEN
                ERROR STOP
        END IF 
END PROGRAM INIT_WRAPPER
