!COPYRIGHT Météo-France 2023
PROGRAM INIT_WRAPPER_INIT_VALUE
        !TEST THAT ALL DATA ARE INITIALIZE TO THE CHOOSEN VALUE
        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        USE OMP_LIB, ONLY: OMP_GET_MAX_THREADS
        IMPLICIT NONE
        CLASS(FIELD_2IM), POINTER :: W => NULL()
        INTEGER(KIND=JPIM), POINTER :: PTR(:,:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: D(:,:)

        ALLOCATE(D(10,10))
        D=1
        CALL FIELD_NEW(W, DATA=D, INIT_VALUE=7_JPIM)
        CALL W%GET_HOST_DATA_RDWR(PTR)
        IF (ANY(W%PTR == 1)) THEN
                ERROR STOP
        END IF 

        CALL FIELD_DELETE(W)
        DEALLOCATE(D)
END PROGRAM INIT_WRAPPER_INIT_VALUE
