PROGRAM INIT
        ! TEST IF PERSISTENT OPTION IS WORKING
        ! WHEN PERSITENT IS SET TO TRUE, LAST DIM OF THE FIELD IS THE NUMBER OF
        ! OPENMP THREADS

        USE FIELD_MODULE
        USE OML_MOD
        IMPLICIT NONE
        TYPE(FIELD_2D_OWNER) :: O

        CALL O%INIT([10,1], [21,11], PERSISTENT=.TRUE.)
        O%PTR=42

        IF (SIZE(O%PTR,1) /= 12) THEN
                ERROR STOP
        END IF
        IF (SIZE(O%PTR,2) /= OML_GET_NUM_THREADS()) THEN
                ERROR STOP
        END IF

        IF (.NOT. ALL(O%PTR == 42)) THEN
                ERROR STOP
        END IF 
END PROGRAM INIT
