PROGRAM INIT_OWNER_INIT_VALUE
        !TEST THAT ALL DATA ARE INITIALIZE TO THE CHOOSEN VALUE
        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        USE OMP_LIB, ONLY: OMP_GET_MAX_THREADS
        USE FIELD_ABORT_MODULE
        IMPLICIT NONE
        CLASS(FIELD_2IM), POINTER :: O => NULL()
        INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

        CALL FIELD_NEW(O, LBOUNDS=[1,1], UBOUNDS=[10,10], INIT_VALUE=7_JPIM)
        CALL O%GET_HOST_DATA_RDWR(PTR)

        WRITE(*,*)O%PTR(1,1)
        IF (.NOT. ALL(O%PTR == 7)) THEN
                CALL FIELD_ABORT ("ERROR")
        END IF

        CALL FIELD_DELETE(O)
END PROGRAM INIT_OWNER_INIT_VALUE
