PROGRAM INIT_OWNER_INIT_VALUE
        !TEST THAT ALL DATA ARE INITIALIZE TO THE CHOOSEN VALUE
        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        USE OMP_LIB, ONLY: OMP_GET_MAX_THREADS
        IMPLICIT NONE
        CLASS(FIELD_2IM), POINTER :: O => NULL()
        INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

        CALL FIELD_NEW(O, LBOUNDS=[1,1], UBOUNDS=[10,10], INIT_VALUE=7_JPIM)
        CALL O%GET_HOST_DATA_RDWR(PTR)

#ifdef INIT_DEBUG_VALUE
        IF (.NOT. ALL(O%PTR == -123456789)) THEN
                ERROR STOP
        END IF
#else
        IF (.NOT. ALL(O%PTR == 7)) THEN
                ERROR STOP
        END IF
#endif

        CALL FIELD_DELETE(O)
END PROGRAM INIT_OWNER_INIT_VALUE
