! (C) Copyright 2022- ECMWF.
! (C) Copyright 2022- Meteo-France.
! (C) Copyright 2023- NVIDIA
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

PROGRAM INIT_WRAPPER_NON_CONTIGUOUS_MULTI
  ! TEST IF WRAPPER WORKS WITH NON CONTIGUOUS ARRAY
  USE FIELD_MODULE
  USE PARKIND1
  USE FIELD_FACTORY_MODULE
  use iso_c_binding

  IMPLICIT NONE
  REAL(KIND=JPRB), ALLOCATABLE, TARGET :: D1(:,:,:,:,:), D2(:,:,:,:,:)
  CLASS(FIELD_2RB), POINTER :: W2 => NULL()
  REAL(KIND=JPRB), POINTER :: W2PTR(:,:)
  CLASS(FIELD_3RB), POINTER :: W3 => NULL()
  REAL(KIND=JPRB), POINTER :: W3PTR(:,:,:)
  CLASS(FIELD_4RB), POINTER :: W4 => NULL()
  REAL(KIND=JPRB), POINTER :: W4PTR(:,:,:,:)
  CLASS(FIELD_5RB), POINTER :: W5 => NULL()
  REAL(KIND=JPRB), POINTER :: W5PTR(:,:,:,:,:)
  integer(kind=8) :: ptr

  ALLOCATE(D1(18, 32, 19, 27, 12))
  ALLOCATE(D2(18, 32, 19, 27, 12))
  D1 = 0
  D2 = 0

  PRINT *, "begin 1"
  CALL FIELD_NEW(W4, DATA=D1(1:1,:,:,:,3))
  CALL W4%GET_HOST_DATA_RDWR(W4PTR)
  W4PTR=42
  CALL W4%GET_DEVICE_DATA_RDWR(W4PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W4PTR=92
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(1:1,:,:,:,3)=92
  CALL W4%GET_HOST_DATA_RDONLY(W4PTR)
  CALL FIELD_DELETE(W4)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 1"
  PRINT *, ""

  PRINT *, "begin 2"
  CALL FIELD_NEW(W3, DATA=D1(:,2,:,:,3))
  CALL W3%GET_HOST_DATA_RDWR(W3PTR)
  W3PTR=51
  CALL W3%GET_DEVICE_DATA_RDWR(W3PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W3PTR=61
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:,2,:,:,3)=61
  CALL FIELD_DELETE(W3)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 2"
  PRINT *, ""

  PRINT *, "begin 3"
  CALL FIELD_NEW(W4, DATA=D1(:,:,4:8,:,3))
  CALL W4%GET_DEVICE_DATA_RDWR(W4PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W4PTR=31
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:,:,4:8,:,3)=31
  CALL FIELD_DELETE(W4)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 3"
  PRINT *, ""

  PRINT *, "begin 4"
  CALL FIELD_NEW(W3, DATA=D1(:,2,4:8,3:5,3))
  CALL W3%GET_DEVICE_DATA_RDWR(W3PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W3PTR=91
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:,2,4:8,3:5,3)=91
  CALL FIELD_DELETE(W3)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 4"
  PRINT *, ""

  PRINT *, "begin 5"
  CALL FIELD_NEW(W2, DATA=D1(:,2,4:8,8,3))
  CALL W2%GET_DEVICE_DATA_RDWR(W2PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W2PTR=12.1
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:,2,4:8,8,3)=12.1
  CALL FIELD_DELETE(W2)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 5"
  PRINT *, ""

  PRINT *, "begin 6"
  CALL FIELD_NEW(W4, DATA=D1(:,:,4,:,:))
  CALL W4%GET_DEVICE_DATA_RDWR(W4PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W4PTR=22.1
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:,:,4,:,:)=22.1
  CALL FIELD_DELETE(W4)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 6"
  PRINT *, ""


  PRINT *, "begin 7"
  CALL FIELD_NEW(W5, DATA=D1(:,1:1,1:1,1:1,1:1))
  CALL W5%GET_DEVICE_DATA_RDWR(W5PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W5PTR=1.1
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:,1:1,1:1,1:1,1:1)=1.1
  CALL FIELD_DELETE(W5)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 7"
  PRINT *, ""

  PRINT *, "begin 8"
  CALL FIELD_NEW(W5, DATA=D1(:3,1:1,3:3,:,2:4))
  CALL W5%GET_DEVICE_DATA_RDWR(W5PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W5PTR=1.2
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:3,1:1,3:3,:,2:4)=1.2
  CALL FIELD_DELETE(W5)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 8"
  PRINT *, ""

  PRINT *, "begin 9"
  CALL FIELD_NEW(W5, DATA=D1(:,1:1,3:3,:,2:4))
  CALL W5%GET_DEVICE_DATA_RDWR(W5PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W5PTR=2.5
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:,1:1,3:3,:,2:4)=2.5
  CALL FIELD_DELETE(W5)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 9"
  PRINT *, ""

  PRINT *, "begin 10"
  CALL FIELD_NEW(W5, DATA=D1(:,1:1,:,1:5,2:4))
  CALL W5%GET_DEVICE_DATA_RDWR(W5PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W5PTR=9.1
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:,1:1,:,1:5,2:4)=9.1
  CALL FIELD_DELETE(W5)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 10"
  PRINT *, ""

  PRINT *, "begin 11"
  CALL FIELD_NEW(W5, DATA=D1(:,1:1,:,8:12,:))
  CALL W5%GET_DEVICE_DATA_RDWR(W5PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W5PTR=8.1
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(:,1:1,:,8:12,:)=8.1
  CALL FIELD_DELETE(W5)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 11"
  PRINT *, ""

  PRINT *, "begin 12"
  CALL FIELD_NEW(W5, DATA=D1(3:7,:,:,:,3:3))
  CALL W5%GET_DEVICE_DATA_RDWR(W5PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W5PTR=8.4
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(3:7,:,:,:,3:3)=8.4
  CALL FIELD_DELETE(W5)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 12"
  PRINT *, ""

  PRINT *, "begin 13"
  CALL FIELD_NEW(W5, DATA=D1(3:3,:,:,:,:))
  CALL W5%GET_DEVICE_DATA_RDWR(W5PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W5PTR=12
  !$ACC END KERNELS
  D1 = -1
  D2 = -1
  D2(3:3,:,:,:,:)=12
  CALL FIELD_DELETE(W5)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 13"
  PRINT *, ""

END PROGRAM INIT_WRAPPER_NON_CONTIGUOUS_MULTI
