PROGRAM NO_TRANSFER
        !TEST THAT DATA OF A FIELD OWNER IS NOT COPIED TO GPU WHEN THEY HAVE NOT
        !BEEN INITIALISED FIRST ON CPU

        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        USE FIELD_ABORT_MODULE
        IMPLICIT NONE
        CLASS(FIELD_2RB), POINTER :: O => NULL()
        REAL(KIND=JPRB), POINTER :: PTR(:,:)
        INTEGER ::I,J

        CALL FIELD_NEW(O, LBOUNDS=[1,1],UBOUNDS=[5,5])
        CALL O%GET_DEVICE_DATA_RDWR(PTR)

        WRITE(*,*)"O%STATS%TRANSFER_CPU_TO_GPU",O%STATS%TRANSFER_CPU_TO_GPU
        WRITE(*,*)"O%STATS%TRANSFER_GPU_TO_CPU",O%STATS%TRANSFER_GPU_TO_CPU
        IF(O%STATS%TRANSFER_CPU_TO_GPU ==1)THEN
                CALL FIELD_ABORT ("ERROR")
        ENDIF

        !$ACC PARALLEL LOOP PRESENT(PTR)
        DO I=1,5
        DO J=1,5
        PTR(I,J)=7
        ENDDO
        ENDDO
        !$ACC END PARALLEL LOOP

        CALL FIELD_DELETE(O)
END PROGRAM NO_TRANSFER
