PROGRAM NO_TRANSFER
        !TEST THAT DATA OF A FIELD OWNER IS NOT COPIED TO CPU WHEN THEY HAVE NOT
        !BEEN INITIALISED FIRST ON CPU OR GPU

        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        USE FIELD_ABORT_MODULE
        IMPLICIT NONE
        CLASS(FIELD_2RB), POINTER :: O => NULL()
        REAL(KIND=JPRB), POINTER :: PTR(:,:)
        INTEGER ::I,J

        CALL FIELD_NEW(O, LBOUNDS=[1,1],UBOUNDS=[5,5], PERSISTENT=.TRUE.)
        CALL O%GET_HOST_DATA_RDWR(PTR)

        WRITE(*,*)"O%STATS%TRANSFER_CPU_TO_GPU",O%STATS%TRANSFER_CPU_TO_GPU
        WRITE(*,*)"O%STATS%TRANSFER_GPU_TO_CPU",O%STATS%TRANSFER_GPU_TO_CPU
        IF(O%STATS%TRANSFER_GPU_TO_CPU /= 0)THEN
                CALL FIELD_ABORT ("ERROR")
        ENDIF

        DO I=1,5
        DO J=1,5
        PTR(I,J)=7
        ENDDO
        ENDDO

        !CALL FIELD_DELETE(O)
END PROGRAM NO_TRANSFER
