!COPYRIGHT Météo-France 2023
PROGRAM SYNC_HOST
        USE FIELD_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        IMPLICIT NONE

        CLASS(FIELD_2RB), POINTER :: W => NULL()
        REAL(KIND=JPRB), ALLOCATABLE :: D(:,:)
        INTEGER :: I, J

        ALLOCATE(D(10,10))
        D=3
        CALL FIELD_NEW(W, DATA=D)
        CALL W%SYNC_DEVICE_RDWR()
        !$ACC KERNELS COPYIN(W) PRESENT(W%DEVPTR)
        DO I=1,10
        DO J=1,10
        W%DEVPTR(I,J) = 7
        ENDDO
        ENDDO
        !$ACC END KERNELS
        CALL FIELD_DELETE(W)
END PROGRAM
