! (C) Copyright 2022- ECMWF.
! (C) Copyright 2022- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

PROGRAM TEST_HDF5_PARALLEL_OUTPUT
        USE FIELD_MODULE
        USE FIELD_HDF5_MODULE
        USE FIELD_FACTORY_MODULE
        USE PARKIND1
        USE FIELD_ABORT_MODULE
        USE HDF5
        USE MPL_MODULE, ONLY: MPL_INIT, MPL_END, MPL_RANK
        USE MPL_DATA_MODULE
        IMPLICIT NONE

        CLASS(FIELD_1RB), POINTER :: FIELD_DATA_1RB => NULL()
        CLASS(FIELD_1RM), POINTER :: FIELD_DATA_1RM => NULL()
        CLASS(FIELD_1RD), POINTER :: FIELD_DATA_1RD => NULL()
        CLASS(FIELD_1IM), POINTER :: FIELD_DATA_1IM => NULL()
        CLASS(FIELD_1LM), POINTER :: FIELD_DATA_1LM => NULL()

        CLASS(FIELD_2RB), POINTER :: FIELD_DATA_2RB => NULL()
        CLASS(FIELD_2RM), POINTER :: FIELD_DATA_2RM => NULL()
        CLASS(FIELD_2RD), POINTER :: FIELD_DATA_2RD => NULL()
        CLASS(FIELD_2IM), POINTER :: FIELD_DATA_2IM => NULL()
        CLASS(FIELD_2LM), POINTER :: FIELD_DATA_2LM => NULL()

        CLASS(FIELD_3RB), POINTER :: FIELD_DATA_3RB => NULL()
        CLASS(FIELD_3RM), POINTER :: FIELD_DATA_3RM => NULL()
        CLASS(FIELD_3RD), POINTER :: FIELD_DATA_3RD => NULL()
        CLASS(FIELD_3IM), POINTER :: FIELD_DATA_3IM => NULL()
        CLASS(FIELD_3LM), POINTER :: FIELD_DATA_3LM => NULL()

        CLASS(FIELD_4RB), POINTER :: FIELD_DATA_4RB => NULL()
        CLASS(FIELD_4RM), POINTER :: FIELD_DATA_4RM => NULL()
        CLASS(FIELD_4RD), POINTER :: FIELD_DATA_4RD => NULL()
        CLASS(FIELD_4IM), POINTER :: FIELD_DATA_4IM => NULL()
        CLASS(FIELD_4LM), POINTER :: FIELD_DATA_4LM => NULL()

        CLASS(FIELD_5RB), POINTER :: FIELD_DATA_5RB => NULL()
        CLASS(FIELD_5RM), POINTER :: FIELD_DATA_5RM => NULL()
        CLASS(FIELD_5RD), POINTER :: FIELD_DATA_5RD => NULL()
        CLASS(FIELD_5IM), POINTER :: FIELD_DATA_5IM => NULL()
        CLASS(FIELD_5LM), POINTER :: FIELD_DATA_5LM => NULL()

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_1RB(:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_1RM(:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_1RD(:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_1IM(:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_1LM(:)

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_2RB(:,:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_2RM(:,:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_2RD(:,:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_2IM(:,:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_2LM(:,:)

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_3RB(:,:,:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_3RM(:,:,:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_3RD(:,:,:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_3IM(:,:,:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_3LM(:,:,:)

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_4RB(:,:,:,:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_4RM(:,:,:,:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_4RD(:,:,:,:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_4IM(:,:,:,:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_4LM(:,:,:,:)

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_5RB(:,:,:,:,:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_5RM(:,:,:,:,:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_5RD(:,:,:,:,:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_5IM(:,:,:,:,:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_5LM(:,:,:,:,:)

        REAL(KIND=JPRB), POINTER :: DATA_CPU_1RB(:)
        REAL(KIND=JPRM), POINTER :: DATA_CPU_1RM(:)
        REAL(KIND=JPRD), POINTER :: DATA_CPU_1RD(:)
        INTEGER(KIND=JPIM), POINTER :: DATA_CPU_1IM(:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_CPU_1LM(:)

        REAL(KIND=JPRB), POINTER :: DATA_CPU_2RB(:,:)
        REAL(KIND=JPRM), POINTER :: DATA_CPU_2RM(:,:)
        REAL(KIND=JPRD), POINTER :: DATA_CPU_2RD(:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_CPU_2IM(:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_CPU_2LM(:,:)

        REAL(KIND=JPRB), POINTER :: DATA_CPU_3RB(:,:,:)
        REAL(KIND=JPRM), POINTER :: DATA_CPU_3RM(:,:,:)
        REAL(KIND=JPRD), POINTER :: DATA_CPU_3RD(:,:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_CPU_3IM(:,:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_CPU_3LM(:,:,:)

        REAL(KIND=JPRB), POINTER :: DATA_CPU_4RB(:,:,:,:)
        REAL(KIND=JPRM), POINTER :: DATA_CPU_4RM(:,:,:,:)
        REAL(KIND=JPRD), POINTER :: DATA_CPU_4RD(:,:,:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_CPU_4IM(:,:,:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_CPU_4LM(:,:,:,:)

        REAL(KIND=JPRB), POINTER :: DATA_CPU_5RB(:,:,:,:,:)
        REAL(KIND=JPRM), POINTER :: DATA_CPU_5RM(:,:,:,:,:)
        REAL(KIND=JPRD), POINTER :: DATA_CPU_5RD(:,:,:,:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_CPU_5IM(:,:,:,:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_CPU_5LM(:,:,:,:,:)

        REAL(KIND=JPRB), POINTER :: DATA_GPU_1RB(:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_1RM(:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_1RD(:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_1IM(:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_1LM(:)

        REAL(KIND=JPRB), POINTER :: DATA_GPU_2RB(:,:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_2RM(:,:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_2RD(:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_2IM(:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_2LM(:,:)

        REAL(KIND=JPRB), POINTER :: DATA_GPU_3RB(:,:,:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_3RM(:,:,:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_3RD(:,:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_3IM(:,:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_3LM(:,:,:)

        REAL(KIND=JPRB), POINTER :: DATA_GPU_4RB(:,:,:,:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_4RM(:,:,:,:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_4RD(:,:,:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_4IM(:,:,:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_4LM(:,:,:,:)

        REAL(KIND=JPRB), POINTER :: DATA_GPU_5RB(:,:,:,:,:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_5RM(:,:,:,:,:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_5RD(:,:,:,:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_5IM(:,:,:,:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_5LM(:,:,:,:,:)

        TYPE(C_PTR) :: D_CPUPTR 
        TYPE(C_PTR) :: DM_CPUPTR 
        TYPE(C_PTR) :: DD_CPUPTR 
        TYPE(C_PTR) :: DI_CPUPTR 
        TYPE(C_PTR) :: DL_CPUPTR 
        INTEGER :: I, J

        ! HDF5 variables
        INTEGER(HID_T) :: file_id, space_id, kind_id
        INTEGER(HID_T) :: dset_id, dsetm_id, dsetd_id,dseti_id,dsetl_id
        INTEGER(HSIZE_T), DIMENSION(2) :: dims
        INTEGER :: hdferr
        INTEGER(JPIM) :: k,l,m 
        INTEGER(JPIM) :: NPROCS
        CHARACTER(LEN=100) :: filename,filenames
        CALL MPL_INIT(KPROCS=NPROCS,LDINFO=.FALSE.,LDENV=.TRUE.)
        WRITE(filenames, '(A,I0)') "field_general"
        filename = TRIM(filename) // ".hdf5"
        filenames = TRIM(filenames) 

        ALLOCATE(DATA_1RB(1))
        ALLOCATE(DATA_1RM(1))
        ALLOCATE(DATA_1RD(1))
        ALLOCATE(DATA_1IM(1))
        ALLOCATE(DATA_1LM(1))

        ALLOCATE(DATA_2RB(2,3))
        ALLOCATE(DATA_2RM(2,3))
        ALLOCATE(DATA_2RD(2,3))
        ALLOCATE(DATA_2IM(2,3))
        ALLOCATE(DATA_2LM(2,3))

        ALLOCATE(DATA_3RB(4,3,2))
        ALLOCATE(DATA_3RM(4,3,2))
        ALLOCATE(DATA_3RD(4,3,2))
        ALLOCATE(DATA_3IM(4,3,2))
        ALLOCATE(DATA_3LM(4,3,2))

        ALLOCATE(DATA_4RB(2,3,1,2))
        ALLOCATE(DATA_4RM(2,3,1,2))
        ALLOCATE(DATA_4RD(2,3,1,2))
        ALLOCATE(DATA_4IM(2,3,1,2))
        ALLOCATE(DATA_4LM(2,3,1,2))

        ALLOCATE(DATA_5RB(3,2,1,2,3))
        ALLOCATE(DATA_5RM(3,2,1,2,3))
        ALLOCATE(DATA_5RD(3,2,1,2,3))
        ALLOCATE(DATA_5IM(3,2,1,2,3))
        ALLOCATE(DATA_5LM(3,2,1,2,3))

        DATA_1RB=[(1.1_JPRB, i = 1, 1)]
        DATA_1RM=[(1.2_JPRM, i = 1, 1)]
        DATA_1RD=[(1.3_JPRD, i = 1, 1)]
        DATA_1IM=[(1_JPIM  , i = 1, 1)]
        DATA_1LM=[(.FALSE. , i = 1, 1)]
        
        DO CONCURRENT(i=1:2, j=1:3)
           DATA_2RB=2.1_JPRB + i*.1_JPRB + j*.01_JPRB
           DATA_2RM=2.2_JPRM + i*.1_JPRM + j*.01_JPRM
           DATA_2RD=2.3_JPRD + i*.1_JPRD + j*.01_JPRD
           DATA_2IM=2_JPIM   + i*10_JPIM + j*100_JPIM
           DATA_2LM=.FALSE.                          
        END DO 
        DATA_2LM(2,2)=.TRUE.

        
        DO CONCURRENT(i=1:4, j=1:3, k=1:2)
           DATA_3RB=3.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB
           DATA_3RM=3.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM
           DATA_3RD=3.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD
           DATA_3IM=3_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM
           DATA_3LM=.FALSE.
        END DO 
        DATA_3LM(3,2,1)=.TRUE.

        DO CONCURRENT(i=1:2, j=1:3, k=1:1, l=1:2)
           DATA_4RB=4.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB
           DATA_4RM=4.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM + l*.0001_JPRM
           DATA_4RD=4.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD + l*.0001_JPRD
           DATA_4IM=4_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM
           DATA_4LM=.FALSE.                                                       
        END DO 
        DATA_4LM(1,2,1,2)=.TRUE.

        DO CONCURRENT(i=1:3, j=1:2, k=1:1, l=1:2, m=1:3)
           DATA_5RB=5.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB + m*.00001_JPRB
           DATA_5RM=5.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRB + l*.0001_JPRB + m*.00001_JPRB
           DATA_5RD=5.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRB + l*.0001_JPRB + m*.00001_JPRB
           DATA_5IM=5_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM + m*100000_JPIM
           DATA_5LM=.FALSE. 
        END DO 
        DATA_5LM(2,1,1,2,3)=.TRUE.

        CALL FIELD_NEW(FIELD_DATA_1RB, DATA=DATA_1RB)
        CALL FIELD_NEW(FIELD_DATA_1RM, DATA=DATA_1RM)
        CALL FIELD_NEW(FIELD_DATA_1RD, DATA=DATA_1RD)
        CALL FIELD_NEW(FIELD_DATA_1IM, DATA=DATA_1IM)
        CALL FIELD_NEW(FIELD_DATA_1LM, DATA=DATA_1LM)

        CALL FIELD_NEW(FIELD_DATA_2RB, DATA=DATA_2RB)
        CALL FIELD_NEW(FIELD_DATA_2RM, DATA=DATA_2RM)
        CALL FIELD_NEW(FIELD_DATA_2RD, DATA=DATA_2RD)
        CALL FIELD_NEW(FIELD_DATA_2IM, DATA=DATA_2IM)
        CALL FIELD_NEW(FIELD_DATA_2LM, DATA=DATA_2LM)

        CALL FIELD_NEW(FIELD_DATA_3RB, DATA=DATA_3RB)
        CALL FIELD_NEW(FIELD_DATA_3RM, DATA=DATA_3RM)
        CALL FIELD_NEW(FIELD_DATA_3RD, DATA=DATA_3RD)
        CALL FIELD_NEW(FIELD_DATA_3IM, DATA=DATA_3IM)
        CALL FIELD_NEW(FIELD_DATA_3LM, DATA=DATA_3LM)

        CALL FIELD_NEW(FIELD_DATA_4RB, DATA=DATA_4RB)
        CALL FIELD_NEW(FIELD_DATA_4RM, DATA=DATA_4RM)
        CALL FIELD_NEW(FIELD_DATA_4RD, DATA=DATA_4RD)
        CALL FIELD_NEW(FIELD_DATA_4IM, DATA=DATA_4IM)
        CALL FIELD_NEW(FIELD_DATA_4LM, DATA=DATA_4LM)

        CALL FIELD_NEW(FIELD_DATA_5RB, DATA=DATA_5RB)
        CALL FIELD_NEW(FIELD_DATA_5RM, DATA=DATA_5RM)
        CALL FIELD_NEW(FIELD_DATA_5RD, DATA=DATA_5RD)
        CALL FIELD_NEW(FIELD_DATA_5IM, DATA=DATA_5IM)
        CALL FIELD_NEW(FIELD_DATA_5LM, DATA=DATA_5LM)

        CALL FIELD_DATA_1RB%GET_DEVICE_DATA_RDWR(DATA_GPU_1RB)
        CALL FIELD_DATA_1RM%GET_DEVICE_DATA_RDWR(DATA_GPU_1RM)
        CALL FIELD_DATA_1RD%GET_DEVICE_DATA_RDWR(DATA_GPU_1RD)
        CALL FIELD_DATA_1IM%GET_DEVICE_DATA_RDWR(DATA_GPU_1IM)
        CALL FIELD_DATA_1LM%GET_DEVICE_DATA_RDWR(DATA_GPU_1LM)

        CALL FIELD_DATA_2RB%GET_DEVICE_DATA_RDWR(DATA_GPU_2RB)
        CALL FIELD_DATA_2RM%GET_DEVICE_DATA_RDWR(DATA_GPU_2RM)
        CALL FIELD_DATA_2RD%GET_DEVICE_DATA_RDWR(DATA_GPU_2RD)
        CALL FIELD_DATA_2IM%GET_DEVICE_DATA_RDWR(DATA_GPU_2IM)
        CALL FIELD_DATA_2LM%GET_DEVICE_DATA_RDWR(DATA_GPU_2LM)

        CALL FIELD_DATA_3RB%GET_DEVICE_DATA_RDWR(DATA_GPU_3RB)
        CALL FIELD_DATA_3RM%GET_DEVICE_DATA_RDWR(DATA_GPU_3RM)
        CALL FIELD_DATA_3RD%GET_DEVICE_DATA_RDWR(DATA_GPU_3RD)
        CALL FIELD_DATA_3IM%GET_DEVICE_DATA_RDWR(DATA_GPU_3IM)
        CALL FIELD_DATA_3LM%GET_DEVICE_DATA_RDWR(DATA_GPU_3LM)

        CALL FIELD_DATA_4RB%GET_DEVICE_DATA_RDWR(DATA_GPU_4RB)
        CALL FIELD_DATA_4RM%GET_DEVICE_DATA_RDWR(DATA_GPU_4RM)
        CALL FIELD_DATA_4RD%GET_DEVICE_DATA_RDWR(DATA_GPU_4RD)
        CALL FIELD_DATA_4IM%GET_DEVICE_DATA_RDWR(DATA_GPU_4IM)
        CALL FIELD_DATA_4LM%GET_DEVICE_DATA_RDWR(DATA_GPU_4LM)

        CALL FIELD_DATA_5RB%GET_DEVICE_DATA_RDWR(DATA_GPU_5RB)
        CALL FIELD_DATA_5RM%GET_DEVICE_DATA_RDWR(DATA_GPU_5RM)
        CALL FIELD_DATA_5RD%GET_DEVICE_DATA_RDWR(DATA_GPU_5RD)
        CALL FIELD_DATA_5IM%GET_DEVICE_DATA_RDWR(DATA_GPU_5IM)
        CALL FIELD_DATA_5LM%GET_DEVICE_DATA_RDWR(DATA_GPU_5LM)

!$ACC KERNELS PRESENT(D_GPU_1RB, DATA_GPU_1RM, DATA_GPU_1RD, DATA_GPU_1IM, DATA_GPU_1LM, &
!$ACC                 D_GPU_2RB, DATA_GPU_2RM, DATA_GPU_2RD, DATA_GPU_2IM, DATA_GPU_2LM, &
!$ACC                 D_GPU_3RB, DATA_GPU_3RM, DATA_GPU_3RD, DATA_GPU_3IM, DATA_GPU_3LM, &
!$ACC                 D_GPU_4RB, DATA_GPU_4RM, DATA_GPU_4RD, DATA_GPU_4IM, DATA_GPU_4LM, &
!$ACC                 D_GPU_5RB, DATA_GPU_5RM, DATA_GPU_5RD, DATA_GPU_5IM, DATA_GPU_5LM)
        DATA_GPU_1RB=[(2.1_JPRB, i = 1, 1)]
        DATA_GPU_1RM=[(2.2_JPRM, i = 1, 1)]
        DATA_GPU_1RD=[(2.3_JPRD, i = 1, 1)]
        DATA_GPU_1IM=[(2_JPIM  , i = 1, 1)]
        DATA_GPU_1LM=[(.FALSE. , i = 1, 1)]
        
        DO CONCURRENT(i=1:2, j=1:3)
           DATA_GPU_2RB(i,j)=3.1_JPRB + i*.1_JPRB + j*.01_JPRB
           DATA_GPU_2RM(i,j)=3.2_JPRM + i*.1_JPRM + j*.01_JPRM
           DATA_GPU_2RD(i,j)=3.3_JPRD + i*.1_JPRD + j*.01_JPRD
           DATA_GPU_2IM(i,j)=3_JPIM   + i*10_JPIM + j*100_JPIM
           DATA_GPU_2LM(i,j)=.FALSE.                          
        END DO 
        DATA_GPU_2LM(2,2)=.TRUE.

        
        DO CONCURRENT(i=1:4, j=1:3, k=1:2)
           DATA_GPU_3RB(i,j,k)=4.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB
           DATA_GPU_3RM(i,j,k)=4.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM
           DATA_GPU_3RD(i,j,k)=4.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD
           DATA_GPU_3IM(i,j,k)=4_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM
           DATA_GPU_3LM=.FALSE.
        END DO 
        DATA_GPU_3LM(3,2,1)=.TRUE.

        DO CONCURRENT(i=1:2, j=1:3, k=1:1, l=1:2)
           DATA_GPU_4RB(i,j,k,l)=5.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB
           DATA_GPU_4RM(i,j,k,l)=5.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM + l*.0001_JPRM
           DATA_GPU_4RD(i,j,k,l)=5.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD + l*.0001_JPRD
           DATA_GPU_4IM(i,j,k,l)=5_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM
           DATA_GPU_4LM=.FALSE.                                                       
        END DO 
        DATA_GPU_4LM(1,2,1,2)=.TRUE.

        DO CONCURRENT(i=1:3, j=1:2, k=1:1, l=1:2, m=1:3)
           DATA_GPU_5RB(i,j,k,l,m)=6.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB + m*.00001_JPRB
           DATA_GPU_5RM(i,j,k,l,m)=6.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRB + l*.0001_JPRB + m*.00001_JPRB
           DATA_GPU_5RD(i,j,k,l,m)=6.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRB + l*.0001_JPRB + m*.00001_JPRB
           DATA_GPU_5IM(i,j,k,l,m)=6_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM + m*100000_JPIM
           DATA_GPU_5LM=.FALSE. 
        END DO 
        DATA_GPU_5LM(2,1,1,2,3)=.TRUE.

        DATA_GPU_1LM=.NOT.DATA_GPU_1LM
        DATA_GPU_2LM=.NOT.DATA_GPU_2LM
        DATA_GPU_3LM=.NOT.DATA_GPU_3LM
        DATA_GPU_4LM=.NOT.DATA_GPU_4LM
        DATA_GPU_5LM=.NOT.DATA_GPU_5LM

!$ACC END KERNELS

!        CALL W%SYNC_HOST_RDONLY()
!        CALL WM%SYNC_HOST_RDONLY()
!        CALL WD%SYNC_HOST_RDONLY()
!        CALL WI%SYNC_HOST_RDONLY()
!        CALL WL%SYNC_HOST_RDONLY()
!        DO I=1,10
!        DO J=1,10
!        IF (D(I,J) /= 7) THEN
!                CALL FIELD_ABORT ("ERROR")
!        ENDIF
!        IF (DM(I,J) /= 8) THEN
!                CALL FIELD_ABORT ("ERROR")
!        ENDIF
!        IF (DD(I,J) /= 9) THEN
!                CALL FIELD_ABORT ("ERROR")
!        ENDIF
!        IF (DI(I,J) /= 2) THEN
!                CALL FIELD_ABORT ("ERROR")
!        ENDIF
!        IF (DL(I,J) .NEQV. .TRUE.) THEN
!                CALL FIELD_ABORT ("ERROR")
!        ENDIF
!        ENDDO
!        ENDDO
!
!        dims = SHAPE(D)  ! Get dimensions of the array
!        CALL W%GET_HOST_DATA_RDWR(D_CPU)
!        CALL WM%GET_HOST_DATA_RDWR(DM_CPU)
!        CALL WD%GET_HOST_DATA_RDWR(DD_CPU)
!        CALL WI%GET_HOST_DATA_RDWR(DI_CPU)
!        CALL WL%GET_HOST_DATA_RDWR(DL_CPU)
!        D_CPUPTR  = C_LOC(D_CPU)
!        DM_CPUPTR = C_LOC(DM_CPU)
!        DD_CPUPTR = C_LOC(DD_CPU)
!        DI_CPUPTR = C_LOC(DI_CPU)
!        DL_CPUPTR = C_LOC(DL_CPU)
!        CALL h5open_f(hdferr)
!        CALL H5Screate_simple_f(2, dims, space_id, hdferr)
!        CALL H5Fcreate_F(filename, H5F_ACC_TRUNC_F, file_id, hdferr)
!        IF(JPRB == JPRD) THEN
!!It is necessary the specialize the code, HDF5 constants must be passed directly
!        CALL H5Dcreate_f(file_id, "W", H5T_NATIVE_DOUBLE, space_id, dset_id, hdferr)
!        CALL H5Dwrite_f(dset_id, H5T_NATIVE_DOUBLE, D_CPUPTR, hdferr)
!        ELSE 
!        CALL H5Dcreate_f(file_id, "W", H5T_NATIVE_REAL, space_id, dsetm_id, hdferr)
!        CALL H5Dwrite_f(dsetm_id, H5T_NATIVE_REAL, D_CPUPTR, hdferr)
!        ENDIF
!        CALL H5Dcreate_f(file_id, "WM", H5T_NATIVE_REAL, space_id, dsetm_id, hdferr)
!        CALL H5Dcreate_f(file_id, "WD", H5T_NATIVE_DOUBLE, space_id, dsetd_id, hdferr)
!        CALL H5Dcreate_f(file_id, "WI", H5T_NATIVE_INTEGER, space_id, dseti_id, hdferr)
!        CALL H5Dcreate_f(file_id, "WL", H5T_NATIVE_INTEGER, space_id, dsetl_id, hdferr)
!        CALL H5Dwrite_f(dsetm_id, H5T_NATIVE_REAL, DM_CPUPTR, hdferr)
!        CALL H5Dwrite_f(dsetd_id, H5T_NATIVE_DOUBLE, DD_CPUPTR, hdferr)
!        CALL H5Dwrite_f(dseti_id, H5T_NATIVE_INTEGER, DI_CPUPTR, hdferr)
!        CALL H5Dwrite_f(dsetl_id, H5T_NATIVE_INTEGER, DL_CPUPTR, hdferr)
!
!        CALL H5Dclose_f(dset_id, hdferr)
!        CALL H5Dclose_f(dsetm_id, hdferr)
!        CALL H5Dclose_f(dsetd_id, hdferr)
!        CALL H5Dclose_f(dseti_id, hdferr)
!        CALL H5Dclose_f(dsetl_id, hdferr)
!        CALL H5Sclose_F(space_id, hdferr)
!        CALL H5Fclose_F(file_id, hdferr)
!
!        DO I=1,10
!        DO J=1,10
!        DL_CPU(I,J) = .FALSE. 
!        ENDDO
!        ENDDO

        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1RB, DATA_CPU_1RB, filenames,"DATA_CPU_1RB")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1RM, DATA_CPU_1RM, filenames,"DATA_CPU_1RM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1RD, DATA_CPU_1RD, filenames,"DATA_CPU_1RD")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1IM, DATA_CPU_1IM, filenames,"DATA_CPU_1IM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1LM, DATA_CPU_1LM, filenames,"DATA_CPU_1LM")

        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2RB, DATA_CPU_2RB, filenames,"DATA_CPU_2RB")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2RM, DATA_CPU_2RM, filenames,"DATA_CPU_2RM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2RD, DATA_CPU_2RD, filenames,"DATA_CPU_2RD")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2IM, DATA_CPU_2IM, filenames,"DATA_CPU_2IM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2LM, DATA_CPU_2LM, filenames,"DATA_CPU_2LM")

        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3RB, DATA_CPU_3RB, filenames,"DATA_CPU_3RB")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3RM, DATA_CPU_3RM, filenames,"DATA_CPU_3RM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3RD, DATA_CPU_3RD, filenames,"DATA_CPU_3RD")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3IM, DATA_CPU_3IM, filenames,"DATA_CPU_3IM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3LM, DATA_CPU_3LM, filenames,"DATA_CPU_3LM")

        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4RB, DATA_CPU_4RB, filenames,"DATA_CPU_4RB")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4RM, DATA_CPU_4RM, filenames,"DATA_CPU_4RM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4RD, DATA_CPU_4RD, filenames,"DATA_CPU_4RD")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4IM, DATA_CPU_4IM, filenames,"DATA_CPU_4IM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4LM, DATA_CPU_4LM, filenames,"DATA_CPU_4LM")

        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5RB, DATA_CPU_5RB, filenames,"DATA_CPU_5RB")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5RM, DATA_CPU_5RM, filenames,"DATA_CPU_5RM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5RD, DATA_CPU_5RD, filenames,"DATA_CPU_5RD")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5IM, DATA_CPU_5IM, filenames,"DATA_CPU_5IM")
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5LM, DATA_CPU_5LM, filenames,"DATA_CPU_5LM")


        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1RB, DATA_GPU_1RB, filenames,"DATA_GPU_1RB", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1RM, DATA_GPU_1RM, filenames,"DATA_GPU_1RM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1RD, DATA_GPU_1RD, filenames,"DATA_GPU_1RD", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1IM, DATA_GPU_1IM, filenames,"DATA_GPU_1IM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_1LM, DATA_GPU_1LM, filenames,"DATA_GPU_1LM", LSYNC=.TRUE.)

        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2RB, DATA_GPU_2RB, filenames,"DATA_GPU_2RB", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2RM, DATA_GPU_2RM, filenames,"DATA_GPU_2RM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2RD, DATA_GPU_2RD, filenames,"DATA_GPU_2RD", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2IM, DATA_GPU_2IM, filenames,"DATA_GPU_2IM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_2LM, DATA_GPU_2LM, filenames,"DATA_GPU_2LM", LSYNC=.TRUE.)

        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3RB, DATA_GPU_3RB, filenames,"DATA_GPU_3RB", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3RM, DATA_GPU_3RM, filenames,"DATA_GPU_3RM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3RD, DATA_GPU_3RD, filenames,"DATA_GPU_3RD", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3IM, DATA_GPU_3IM, filenames,"DATA_GPU_3IM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_3LM, DATA_GPU_3LM, filenames,"DATA_GPU_3LM", LSYNC=.TRUE.)

        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4RB, DATA_GPU_4RB, filenames,"DATA_GPU_4RB", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4RM, DATA_GPU_4RM, filenames,"DATA_GPU_4RM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4RD, DATA_GPU_4RD, filenames,"DATA_GPU_4RD", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4IM, DATA_GPU_4IM, filenames,"DATA_GPU_4IM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_4LM, DATA_GPU_4LM, filenames,"DATA_GPU_4LM", LSYNC=.TRUE.)

        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5RB, DATA_GPU_5RB, filenames,"DATA_GPU_5RB", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5RM, DATA_GPU_5RM, filenames,"DATA_GPU_5RM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5RD, DATA_GPU_5RD, filenames,"DATA_GPU_5RD", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5IM, DATA_GPU_5IM, filenames,"DATA_GPU_5IM", LSYNC=.TRUE.)
        CALL GET_HDF5_PERRANK_DATA(FIELD_DATA_5LM, DATA_GPU_5LM, filenames,"DATA_GPU_5LM", LSYNC=.TRUE.)

        PRINT *,'MPL_WORLD_RANK',MPL_WORLD_RANK,MPL_RANK
        CALL MPL_END(LDMEMINFO=.FALSE.)

        CALL FIELD_DELETE(FIELD_DATA_1RB)
        CALL FIELD_DELETE(FIELD_DATA_1RM)
        CALL FIELD_DELETE(FIELD_DATA_1RD)
        CALL FIELD_DELETE(FIELD_DATA_1IM)
        CALL FIELD_DELETE(FIELD_DATA_1LM)

        CALL FIELD_DELETE(FIELD_DATA_2RB)
        CALL FIELD_DELETE(FIELD_DATA_2RM)
        CALL FIELD_DELETE(FIELD_DATA_2RD)
        CALL FIELD_DELETE(FIELD_DATA_2IM)
        CALL FIELD_DELETE(FIELD_DATA_2LM)

        CALL FIELD_DELETE(FIELD_DATA_3RB)
        CALL FIELD_DELETE(FIELD_DATA_3RM)
        CALL FIELD_DELETE(FIELD_DATA_3RD)
        CALL FIELD_DELETE(FIELD_DATA_3IM)
        CALL FIELD_DELETE(FIELD_DATA_3LM)

        CALL FIELD_DELETE(FIELD_DATA_4RB)
        CALL FIELD_DELETE(FIELD_DATA_4RM)
        CALL FIELD_DELETE(FIELD_DATA_4RD)
        CALL FIELD_DELETE(FIELD_DATA_4IM)
        CALL FIELD_DELETE(FIELD_DATA_4LM)

        CALL FIELD_DELETE(FIELD_DATA_5RB)
        CALL FIELD_DELETE(FIELD_DATA_5RM)
        CALL FIELD_DELETE(FIELD_DATA_5RD)
        CALL FIELD_DELETE(FIELD_DATA_5IM)
        CALL FIELD_DELETE(FIELD_DATA_5LM)
END PROGRAM
