! (C) Copyright 2022- ECMWF.
! (C) Copyright 2022- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

PROGRAM TEST_HDF5_PARALLEL_OUTPUT
        USE PARKIND1, ONLY: JPRB, JPRM, JPRD, JPIM, JPLM
        USE FIELD_FACTORY_MODULE
        USE FIELD_MODULE, ONLY: FIELD_1RB, FIELD_1RM, FIELD_1RD, FIELD_1IM, FIELD_1LM
        USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_2RM, FIELD_2RD, FIELD_2IM, FIELD_2LM
        USE FIELD_MODULE, ONLY: FIELD_3RB, FIELD_3RM, FIELD_3RD, FIELD_3IM, FIELD_3LM
        USE FIELD_MODULE, ONLY: FIELD_4RB, FIELD_4RM, FIELD_4RD, FIELD_4IM, FIELD_4LM
        USE FIELD_MODULE, ONLY: FIELD_5RB, FIELD_5RM, FIELD_5RD, FIELD_5IM, FIELD_5LM
        USE FIELD_HDF5_MODULE, ONLY:  WRITE_HDF5_PERRANK_DATA, READ_HDF5_PERRANK_DATA
        USE FIELD_ABORT_MODULE, ONLY: FIELD_ABORT
        USE HDF5, ONLY: HSIZE_T, HID_T
        USE ISO_C_BINDING, ONLY : C_PTR, C_LOC
#if(HAVE_MPI)
        USE MPI, ONLY: MPI_INIT, MPI_FINALIZE
#endif

        IMPLICIT NONE

        CLASS(FIELD_1RB), POINTER :: FIELD_DATA_1RB => NULL()
        CLASS(FIELD_1RM), POINTER :: FIELD_DATA_1RM => NULL()
        CLASS(FIELD_1RD), POINTER :: FIELD_DATA_1RD => NULL()
        CLASS(FIELD_1IM), POINTER :: FIELD_DATA_1IM => NULL()
        CLASS(FIELD_1LM), POINTER :: FIELD_DATA_1LM => NULL()

        CLASS(FIELD_2RB), POINTER :: FIELD_DATA_2RB => NULL()
        CLASS(FIELD_2RM), POINTER :: FIELD_DATA_2RM => NULL()
        CLASS(FIELD_2RD), POINTER :: FIELD_DATA_2RD => NULL()
        CLASS(FIELD_2IM), POINTER :: FIELD_DATA_2IM => NULL()
        CLASS(FIELD_2LM), POINTER :: FIELD_DATA_2LM => NULL()

        CLASS(FIELD_3RB), POINTER :: FIELD_DATA_3RB => NULL()
        CLASS(FIELD_3RM), POINTER :: FIELD_DATA_3RM => NULL()
        CLASS(FIELD_3RD), POINTER :: FIELD_DATA_3RD => NULL()
        CLASS(FIELD_3IM), POINTER :: FIELD_DATA_3IM => NULL()
        CLASS(FIELD_3LM), POINTER :: FIELD_DATA_3LM => NULL()

        CLASS(FIELD_4RB), POINTER :: FIELD_DATA_4RB => NULL()
        CLASS(FIELD_4RM), POINTER :: FIELD_DATA_4RM => NULL()
        CLASS(FIELD_4RD), POINTER :: FIELD_DATA_4RD => NULL()
        CLASS(FIELD_4IM), POINTER :: FIELD_DATA_4IM => NULL()
        CLASS(FIELD_4LM), POINTER :: FIELD_DATA_4LM => NULL()

        CLASS(FIELD_5RB), POINTER :: FIELD_DATA_5RB => NULL()
        CLASS(FIELD_5RM), POINTER :: FIELD_DATA_5RM => NULL()
        CLASS(FIELD_5RD), POINTER :: FIELD_DATA_5RD => NULL()
        CLASS(FIELD_5IM), POINTER :: FIELD_DATA_5IM => NULL()
        CLASS(FIELD_5LM), POINTER :: FIELD_DATA_5LM => NULL()

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_1RB(:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_1RM(:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_1RD(:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_1IM(:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_1LM(:)

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_2RB(:,:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_2RM(:,:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_2RD(:,:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_2IM(:,:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_2LM(:,:)

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_3RB(:,:,:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_3RM(:,:,:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_3RD(:,:,:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_3IM(:,:,:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_3LM(:,:,:)

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_4RB(:,:,:,:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_4RM(:,:,:,:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_4RD(:,:,:,:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_4IM(:,:,:,:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_4LM(:,:,:,:)

        REAL(KIND=JPRB), ALLOCATABLE :: DATA_5RB(:,:,:,:,:)
        REAL(KIND=JPRM), ALLOCATABLE :: DATA_5RM(:,:,:,:,:)
        REAL(KIND=JPRD), ALLOCATABLE :: DATA_5RD(:,:,:,:,:)
        INTEGER(KIND=JPIM), ALLOCATABLE :: DATA_5IM(:,:,:,:,:)
        LOGICAL(KIND=JPLM), ALLOCATABLE :: DATA_5LM(:,:,:,:,:)


        REAL(KIND=JPRB), POINTER :: DATA_GPU_1RB(:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_1RM(:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_1RD(:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_1IM(:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_1LM(:)

        REAL(KIND=JPRB), POINTER :: DATA_GPU_2RB(:,:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_2RM(:,:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_2RD(:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_2IM(:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_2LM(:,:)

        REAL(KIND=JPRB), POINTER :: DATA_GPU_3RB(:,:,:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_3RM(:,:,:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_3RD(:,:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_3IM(:,:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_3LM(:,:,:)

        REAL(KIND=JPRB), POINTER :: DATA_GPU_4RB(:,:,:,:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_4RM(:,:,:,:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_4RD(:,:,:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_4IM(:,:,:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_4LM(:,:,:,:)

        REAL(KIND=JPRB), POINTER :: DATA_GPU_5RB(:,:,:,:,:)
        REAL(KIND=JPRM), POINTER :: DATA_GPU_5RM(:,:,:,:,:)
        REAL(KIND=JPRD), POINTER :: DATA_GPU_5RD(:,:,:,:,:)
        INTEGER(KIND=JPIM), POINTER :: DATA_GPU_5IM(:,:,:,:,:)
        LOGICAL(KIND=JPLM), POINTER :: DATA_GPU_5LM(:,:,:,:,:)

        TYPE(C_PTR) :: D_CPUPTR 
        TYPE(C_PTR) :: DM_CPUPTR 
        TYPE(C_PTR) :: DD_CPUPTR 
        TYPE(C_PTR) :: DI_CPUPTR 
        TYPE(C_PTR) :: DL_CPUPTR 
        INTEGER :: I, J
        INTEGER :: mpierr

        ! HDF5 variables
        INTEGER(HID_T) :: file_id, space_id, kind_id
        INTEGER(HID_T) :: dset_id, dsetm_id, dsetd_id,dseti_id,dsetl_id
        INTEGER(HSIZE_T), DIMENSION(2) :: dims
        INTEGER :: hdferr
        INTEGER(JPIM) :: k,l,m 
        CHARACTER(LEN=100) :: h5filename
#if(HAVE_MPI)
        CALL MPI_INIT(mpierr)
#endif
        WRITE(h5filename, '(A,I0)') "field_general"
        h5filename = TRIM(h5filename) 

        ALLOCATE(DATA_1RB(1))
        ALLOCATE(DATA_1RM(1))
        ALLOCATE(DATA_1RD(1))
        ALLOCATE(DATA_1IM(1))
        ALLOCATE(DATA_1LM(1))

        ALLOCATE(DATA_2RB(2,3))
        ALLOCATE(DATA_2RM(2,3))
        ALLOCATE(DATA_2RD(2,3))
        ALLOCATE(DATA_2IM(2,3))
        ALLOCATE(DATA_2LM(2,3))

        ALLOCATE(DATA_3RB(4,3,2))
        ALLOCATE(DATA_3RM(4,3,2))
        ALLOCATE(DATA_3RD(4,3,2))
        ALLOCATE(DATA_3IM(4,3,2))
        ALLOCATE(DATA_3LM(4,3,2))

        ALLOCATE(DATA_4RB(2,3,1,2))
        ALLOCATE(DATA_4RM(2,3,1,2))
        ALLOCATE(DATA_4RD(2,3,1,2))
        ALLOCATE(DATA_4IM(2,3,1,2))
        ALLOCATE(DATA_4LM(2,3,1,2))

        ALLOCATE(DATA_5RB(3,2,1,2,3))
        ALLOCATE(DATA_5RM(3,2,1,2,3))
        ALLOCATE(DATA_5RD(3,2,1,2,3))
        ALLOCATE(DATA_5IM(3,2,1,2,3))
        ALLOCATE(DATA_5LM(3,2,1,2,3))

        DATA_1RB = [(1.1_JPRB, i = 1, 1)]
        DATA_1RM = [(1.2_JPRM, i = 1, 1)]
        DATA_1RD = [(1.3_JPRD, i = 1, 1)]
        DATA_1IM = [(1_JPIM  , i = 1, 1)]
        DATA_1LM = [(.FALSE. , i = 1, 1)]
        
        DO CONCURRENT(i=1:2, j=1:3)
           DATA_2RB(i,j) = 2.1_JPRB + i*.1_JPRB + j*.01_JPRB
           DATA_2RM(i,j) = 2.2_JPRM + i*.1_JPRM + j*.01_JPRM
           DATA_2RD(i,j) = 2.3_JPRD + i*.1_JPRD + j*.01_JPRD
           DATA_2IM(i,j) = 2_JPIM   + i*10_JPIM + j*100_JPIM
           DATA_2LM(i,j) = .FALSE.
        END DO 
        DATA_2LM(2,2) = .TRUE.

        
        DO CONCURRENT(i=1:4, j=1:3, k=1:2)
           DATA_3RB(i,j,k) = 3.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB
           DATA_3RM(i,j,k) = 3.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM
           DATA_3RD(i,j,k) = 3.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD
           DATA_3IM(i,j,k) = 3_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM
           DATA_3LM(i,j,k) = .FALSE.
        END DO 
        DATA_3LM(3,2,1) = .TRUE.

        DO CONCURRENT(i=1:2, j=1:3, k=1:1, l=1:2)
           DATA_4RB(i,j,k,l) = 4.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB
           DATA_4RM(i,j,k,l) = 4.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM + l*.0001_JPRM
           DATA_4RD(i,j,k,l) = 4.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD + l*.0001_JPRD
           DATA_4IM(i,j,k,l) = 4_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM
           DATA_4LM(i,j,k,l) = .FALSE.
        END DO 
        DATA_4LM(1,2,1,2) = .TRUE.

        DO CONCURRENT(i=1:3, j=1:2, k=1:1, l=1:2, m=1:3)
           DATA_5RB(i,j,k,l,m) = 5.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB + m*.00001_JPRB
           DATA_5RM(i,j,k,l,m) = 5.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM + l*.0001_JPRM + m*.00001_JPRM
           DATA_5RD(i,j,k,l,m) = 5.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD + l*.0001_JPRD + m*.00001_JPRD
           DATA_5IM(i,j,k,l,m) = 5_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM + m*100000_JPIM
           DATA_5LM(i,j,k,l,m) = .FALSE.
        END DO 
        DATA_5LM(2,1,1,2,3) = .TRUE.

        CALL FIELD_NEW(FIELD_DATA_1RB, DATA=DATA_1RB)
        CALL FIELD_NEW(FIELD_DATA_1RM, DATA=DATA_1RM)
        CALL FIELD_NEW(FIELD_DATA_1RD, DATA=DATA_1RD)
        CALL FIELD_NEW(FIELD_DATA_1IM, DATA=DATA_1IM)
        CALL FIELD_NEW(FIELD_DATA_1LM, DATA=DATA_1LM)

        CALL FIELD_NEW(FIELD_DATA_2RB, DATA=DATA_2RB)
        CALL FIELD_NEW(FIELD_DATA_2RM, DATA=DATA_2RM)
        CALL FIELD_NEW(FIELD_DATA_2RD, DATA=DATA_2RD)
        CALL FIELD_NEW(FIELD_DATA_2IM, DATA=DATA_2IM)
        CALL FIELD_NEW(FIELD_DATA_2LM, DATA=DATA_2LM)

        CALL FIELD_NEW(FIELD_DATA_3RB, DATA=DATA_3RB)
        CALL FIELD_NEW(FIELD_DATA_3RM, DATA=DATA_3RM)
        CALL FIELD_NEW(FIELD_DATA_3RD, DATA=DATA_3RD)
        CALL FIELD_NEW(FIELD_DATA_3IM, DATA=DATA_3IM)
        CALL FIELD_NEW(FIELD_DATA_3LM, DATA=DATA_3LM)

        CALL FIELD_NEW(FIELD_DATA_4RB, DATA=DATA_4RB)
        CALL FIELD_NEW(FIELD_DATA_4RM, DATA=DATA_4RM)
        CALL FIELD_NEW(FIELD_DATA_4RD, DATA=DATA_4RD)
        CALL FIELD_NEW(FIELD_DATA_4IM, DATA=DATA_4IM)
        CALL FIELD_NEW(FIELD_DATA_4LM, DATA=DATA_4LM)

        CALL FIELD_NEW(FIELD_DATA_5RB, DATA=DATA_5RB)
        CALL FIELD_NEW(FIELD_DATA_5RM, DATA=DATA_5RM)
        CALL FIELD_NEW(FIELD_DATA_5RD, DATA=DATA_5RD)
        CALL FIELD_NEW(FIELD_DATA_5IM, DATA=DATA_5IM)
        CALL FIELD_NEW(FIELD_DATA_5LM, DATA=DATA_5LM)

        CALL FIELD_DATA_1RB%GET_DEVICE_DATA_RDWR(DATA_GPU_1RB)
        CALL FIELD_DATA_1RM%GET_DEVICE_DATA_RDWR(DATA_GPU_1RM)
        CALL FIELD_DATA_1RD%GET_DEVICE_DATA_RDWR(DATA_GPU_1RD)
        CALL FIELD_DATA_1IM%GET_DEVICE_DATA_RDWR(DATA_GPU_1IM)
        CALL FIELD_DATA_1LM%GET_DEVICE_DATA_RDWR(DATA_GPU_1LM)

        CALL FIELD_DATA_2RB%GET_DEVICE_DATA_RDWR(DATA_GPU_2RB)
        CALL FIELD_DATA_2RM%GET_DEVICE_DATA_RDWR(DATA_GPU_2RM)
        CALL FIELD_DATA_2RD%GET_DEVICE_DATA_RDWR(DATA_GPU_2RD)
        CALL FIELD_DATA_2IM%GET_DEVICE_DATA_RDWR(DATA_GPU_2IM)
        CALL FIELD_DATA_2LM%GET_DEVICE_DATA_RDWR(DATA_GPU_2LM)

        CALL FIELD_DATA_3RB%GET_DEVICE_DATA_RDWR(DATA_GPU_3RB)
        CALL FIELD_DATA_3RM%GET_DEVICE_DATA_RDWR(DATA_GPU_3RM)
        CALL FIELD_DATA_3RD%GET_DEVICE_DATA_RDWR(DATA_GPU_3RD)
        CALL FIELD_DATA_3IM%GET_DEVICE_DATA_RDWR(DATA_GPU_3IM)
        CALL FIELD_DATA_3LM%GET_DEVICE_DATA_RDWR(DATA_GPU_3LM)

        CALL FIELD_DATA_4RB%GET_DEVICE_DATA_RDWR(DATA_GPU_4RB)
        CALL FIELD_DATA_4RM%GET_DEVICE_DATA_RDWR(DATA_GPU_4RM)
        CALL FIELD_DATA_4RD%GET_DEVICE_DATA_RDWR(DATA_GPU_4RD)
        CALL FIELD_DATA_4IM%GET_DEVICE_DATA_RDWR(DATA_GPU_4IM)
        CALL FIELD_DATA_4LM%GET_DEVICE_DATA_RDWR(DATA_GPU_4LM)

        CALL FIELD_DATA_5RB%GET_DEVICE_DATA_RDWR(DATA_GPU_5RB)
        CALL FIELD_DATA_5RM%GET_DEVICE_DATA_RDWR(DATA_GPU_5RM)
        CALL FIELD_DATA_5RD%GET_DEVICE_DATA_RDWR(DATA_GPU_5RD)
        CALL FIELD_DATA_5IM%GET_DEVICE_DATA_RDWR(DATA_GPU_5IM)
        CALL FIELD_DATA_5LM%GET_DEVICE_DATA_RDWR(DATA_GPU_5LM)

#ifdef OMPGPU
!$OMP TARGET MAP(TO: &
!$OMP                 DATA_GPU_1RB, DATA_GPU_1RM, DATA_GPU_1RD, DATA_GPU_1IM, DATA_GPU_1LM, &
!$OMP                 DATA_GPU_2RB, DATA_GPU_2RM, DATA_GPU_2RD, DATA_GPU_2IM, DATA_GPU_2LM, &
!$OMP                 DATA_GPU_3RB, DATA_GPU_3RM, DATA_GPU_3RD, DATA_GPU_3IM, DATA_GPU_3LM, &
!$OMP                 DATA_GPU_4RB, DATA_GPU_4RM, DATA_GPU_4RD, DATA_GPU_4IM, DATA_GPU_4LM, &
!$OMP                 DATA_GPU_5RB, DATA_GPU_5RM, DATA_GPU_5RD, DATA_GPU_5IM, DATA_GPU_5LM) 
#else
!$ACC KERNELS PRESENT(DATA_GPU_1RB, DATA_GPU_1RM, DATA_GPU_1RD, DATA_GPU_1IM, DATA_GPU_1LM, &
!$ACC                 DATA_GPU_2RB, DATA_GPU_2RM, DATA_GPU_2RD, DATA_GPU_2IM, DATA_GPU_2LM, &
!$ACC                 DATA_GPU_3RB, DATA_GPU_3RM, DATA_GPU_3RD, DATA_GPU_3IM, DATA_GPU_3LM, &
!$ACC                 DATA_GPU_4RB, DATA_GPU_4RM, DATA_GPU_4RD, DATA_GPU_4IM, DATA_GPU_4LM, &
!$ACC                 DATA_GPU_5RB, DATA_GPU_5RM, DATA_GPU_5RD, DATA_GPU_5IM, DATA_GPU_5LM)
#endif

        DATA_GPU_1RB = 2.1_JPRB
        DATA_GPU_1RM = 2.2_JPRM
        DATA_GPU_1RD = 2.3_JPRD
        DATA_GPU_1IM = 2_JPIM  
        DATA_GPU_1LM = .FALSE. 
        
        DO CONCURRENT(i=1:2, j=1:3)
           DATA_GPU_2RB(i,j) = 3.1_JPRB + i*.1_JPRB + j*.01_JPRB
           DATA_GPU_2RM(i,j) = 3.2_JPRM + i*.1_JPRM + j*.01_JPRM
           DATA_GPU_2RD(i,j) = 3.3_JPRD + i*.1_JPRD + j*.01_JPRD
           DATA_GPU_2IM(i,j) = 3_JPIM   + i*10_JPIM + j*100_JPIM
           DATA_GPU_2LM(i,j) = .FALSE.
        END DO 
        DATA_GPU_2LM(2,2) = .TRUE.

        DO CONCURRENT(i=1:4, j=1:3, k=1:2)
           DATA_GPU_3RB(i,j,k) = 4.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB
           DATA_GPU_3RM(i,j,k) = 4.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM
           DATA_GPU_3RD(i,j,k) = 4.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD
           DATA_GPU_3IM(i,j,k) = 4_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM
           DATA_GPU_3LM(i,j,k) = .FALSE.
        END DO 
        DATA_GPU_3LM(3,2,1) = .TRUE.

        DO CONCURRENT(i=1:2, j=1:3, k=1:1, l=1:2)
           DATA_GPU_4RB(i,j,k,l) = 5.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB
           DATA_GPU_4RM(i,j,k,l) = 5.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM + l*.0001_JPRM
           DATA_GPU_4RD(i,j,k,l) = 5.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD + l*.0001_JPRD
           DATA_GPU_4IM(i,j,k,l) = 5_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM
           DATA_GPU_4LM(i,j,k,l) = .FALSE.
        END DO 
        DATA_GPU_4LM(1,2,1,2) = .TRUE.

        DO CONCURRENT(i=1:3, j=1:2, k=1:1, l=1:2, m=1:3)
           DATA_GPU_5RB(i,j,k,l,m) = 6.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB + m*.00001_JPRB
           DATA_GPU_5RM(i,j,k,l,m) = 6.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM + l*.0001_JPRM + m*.00001_JPRM
           DATA_GPU_5RD(i,j,k,l,m) = 6.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD + l*.0001_JPRD + m*.00001_JPRD
           DATA_GPU_5IM(i,j,k,l,m) = 6_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM + m*100000_JPIM
           DATA_GPU_5LM(i,j,k,l,m) = .FALSE.
        END DO 
        DATA_GPU_5LM(2,1,1,2,3) = .TRUE.

        DATA_GPU_1LM=.NOT.DATA_GPU_1LM
        DATA_GPU_2LM=.NOT.DATA_GPU_2LM
        DATA_GPU_3LM=.NOT.DATA_GPU_3LM
        DATA_GPU_4LM=.NOT.DATA_GPU_4LM
        DATA_GPU_5LM=.NOT.DATA_GPU_5LM

#ifdef OMPGPU
!$OMP END TARGET  
#else
!$ACC END KERNELS
#endif

        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1RB, h5filename, "DATA_CPU_1RB")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1RM, h5filename, "DATA_CPU_1RM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1RD, h5filename, "DATA_CPU_1RD")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1IM, h5filename, "DATA_CPU_1IM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1LM, h5filename, "DATA_CPU_1LM")

        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2RB, h5filename, "DATA_CPU_2RB")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2RM, h5filename, "DATA_CPU_2RM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2RD, h5filename, "DATA_CPU_2RD")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2IM, h5filename, "DATA_CPU_2IM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2LM, h5filename, "DATA_CPU_2LM")

        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3RB, h5filename, "DATA_CPU_3RB")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3RM, h5filename, "DATA_CPU_3RM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3RD, h5filename, "DATA_CPU_3RD")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3IM, h5filename, "DATA_CPU_3IM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3LM, h5filename, "DATA_CPU_3LM")

        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4RB, h5filename, "DATA_CPU_4RB")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4RM, h5filename, "DATA_CPU_4RM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4RD, h5filename, "DATA_CPU_4RD")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4IM, h5filename, "DATA_CPU_4IM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4LM, h5filename, "DATA_CPU_4LM")

        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5RB, h5filename, "DATA_CPU_5RB")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5RM, h5filename, "DATA_CPU_5RM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5RD, h5filename, "DATA_CPU_5RD")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5IM, h5filename, "DATA_CPU_5IM")
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5LM, h5filename, "DATA_CPU_5LM")


        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1RB, h5filename, "DATA_GPU_1RB", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1RM, h5filename, "DATA_GPU_1RM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1RD, h5filename, "DATA_GPU_1RD", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1IM, h5filename, "DATA_GPU_1IM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_1LM, h5filename, "DATA_GPU_1LM", LSYNC=.TRUE.)

        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2RB, h5filename, "DATA_GPU_2RB", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2RM, h5filename, "DATA_GPU_2RM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2RD, h5filename, "DATA_GPU_2RD", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2IM, h5filename, "DATA_GPU_2IM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_2LM, h5filename, "DATA_GPU_2LM", LSYNC=.TRUE.)

        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3RB, h5filename, "DATA_GPU_3RB", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3RM, h5filename, "DATA_GPU_3RM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3RD, h5filename, "DATA_GPU_3RD", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3IM, h5filename, "DATA_GPU_3IM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_3LM, h5filename, "DATA_GPU_3LM", LSYNC=.TRUE.)

        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4RB, h5filename, "DATA_GPU_4RB", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4RM, h5filename, "DATA_GPU_4RM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4RD, h5filename, "DATA_GPU_4RD", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4IM, h5filename, "DATA_GPU_4IM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_4LM, h5filename, "DATA_GPU_4LM", LSYNC=.TRUE.)

        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5RB, h5filename, "DATA_GPU_5RB", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5RM, h5filename, "DATA_GPU_5RM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5RD, h5filename, "DATA_GPU_5RD", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5IM, h5filename, "DATA_GPU_5IM", LSYNC=.TRUE.)
        CALL WRITE_HDF5_PERRANK_DATA(FIELD_DATA_5LM, h5filename, "DATA_GPU_5LM", LSYNC=.TRUE.)


        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_1RB, h5filename, "DATA_CPU_1RB")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_1RM, h5filename, "DATA_CPU_1RM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_1RD, h5filename, "DATA_CPU_1RD")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_1IM, h5filename, "DATA_CPU_1IM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_1LM, h5filename, "DATA_CPU_1LM")

        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_2RB, h5filename, "DATA_CPU_2RB")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_2RM, h5filename, "DATA_CPU_2RM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_2RD, h5filename, "DATA_CPU_2RD")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_2IM, h5filename, "DATA_CPU_2IM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_2LM, h5filename, "DATA_CPU_2LM")

        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_3RB, h5filename, "DATA_CPU_3RB")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_3RM, h5filename, "DATA_CPU_3RM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_3RD, h5filename, "DATA_CPU_3RD")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_3IM, h5filename, "DATA_CPU_3IM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_3LM, h5filename, "DATA_CPU_3LM")

        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_4RB, h5filename, "DATA_CPU_4RB")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_4RM, h5filename, "DATA_CPU_4RM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_4RD, h5filename, "DATA_CPU_4RD")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_4IM, h5filename, "DATA_CPU_4IM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_4LM, h5filename, "DATA_CPU_4LM")

        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_5RB, h5filename, "DATA_CPU_5RB")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_5RM, h5filename, "DATA_CPU_5RM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_5RD, h5filename, "DATA_CPU_5RD")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_5IM, h5filename, "DATA_CPU_5IM")
        CALL READ_HDF5_PERRANK_DATA(FIELD_DATA_5LM, h5filename, "DATA_CPU_5LM")

        DATA_1RB = DATA_1RB-[(1.1_JPRB, i = 1, 1)]
        DATA_1RM = DATA_1RM-[(1.2_JPRM, i = 1, 1)]
        DATA_1RD = DATA_1RD-[(1.3_JPRD, i = 1, 1)]
        DATA_1IM = DATA_1IM-[(1_JPIM  , i = 1, 1)]
        DATA_1LM = .NOT.(DATA_1LM.EQV.[(.FALSE. , i = 1, 1)])

        DO CONCURRENT(i=1:2, j=1:3)
           DATA_2RB(i,j) = 2.1_JPRB + i*.1_JPRB + j*.01_JPRB - DATA_2RB(i,j)
           DATA_2RM(i,j) = 2.2_JPRM + i*.1_JPRM + j*.01_JPRM - DATA_2RM(i,j)
           DATA_2RD(i,j) = 2.3_JPRD + i*.1_JPRD + j*.01_JPRD - DATA_2RD(i,j)
           DATA_2IM(i,j) = 2_JPIM   + i*10_JPIM + j*100_JPIM - DATA_2IM(i,j)
           DATA_2LM(i,j) = .NOT.(.FALSE. .EQV. DATA_2LM(i,j))
        END DO
        DATA_2LM(2,2) = .NOT.(.TRUE. .EQV. DATA_2LM(2,2))

        DO CONCURRENT(i=1:4, j=1:3, k=1:2)
           DATA_3RB(i,j,k) = 3.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB - DATA_3RB(i,j,k)
           DATA_3RM(i,j,k) = 3.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM - DATA_3RM(i,j,k)
           DATA_3RD(i,j,k) = 3.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD - DATA_3RD(i,j,k)
           DATA_3IM(i,j,k) = 3_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM - DATA_3IM(i,j,k)
           DATA_3LM(i,j,k) = .NOT. (.FALSE. .EQV. DATA_3LM(i,j,k))
        END DO
        DATA_3LM(3,2,1) = .NOT. (.TRUE. .EQV. DATA_3LM(3,2,1))

        DO CONCURRENT(i=1:2, j=1:3, k=1:1, l=1:2)
           DATA_4RB(i,j,k,l) = 4.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB - DATA_4RB(i,j,k,l)
           DATA_4RM(i,j,k,l) = 4.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM + l*.0001_JPRM - DATA_4RM(i,j,k,l)
           DATA_4RD(i,j,k,l) = 4.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD + l*.0001_JPRD - DATA_4RD(i,j,k,l)
           DATA_4IM(i,j,k,l) = 4_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM - DATA_4IM(i,j,k,l)
           DATA_4LM(i,j,k,l) = .NOT. (.FALSE. .EQV.  DATA_4LM(i,j,k,l))
        END DO
        DATA_4LM(1,2,1,2) = .NOT. (.TRUE. .EQV. DATA_4LM(1,2,1,2))

        DO CONCURRENT(i=1:3, j=1:2, k=1:1, l=1:2, m=1:3)
           DATA_5RB(i,j,k,l,m) = 5.1_JPRB + i*.1_JPRB + j*.01_JPRB + k*.001_JPRB + l*.0001_JPRB + m*.00001_JPRB &
                                                                                          & - DATA_5RB(i,j,k,l,m)
           DATA_5RM(i,j,k,l,m) = 5.2_JPRM + i*.1_JPRM + j*.01_JPRM + k*.001_JPRM + l*.0001_JPRM + m*.00001_JPRM &
                                                                                          & - DATA_5RM(i,j,k,l,m)
           DATA_5RD(i,j,k,l,m) = 5.3_JPRD + i*.1_JPRD + j*.01_JPRD + k*.001_JPRD + l*.0001_JPRD + m*.00001_JPRD &
                                                                                          & - DATA_5RD(i,j,k,l,m)
           DATA_5IM(i,j,k,l,m) = 5_JPIM   + i*10_JPIM + j*100_JPIM + k*1000_JPIM + l*10000_JPIM + m*100000_JPIM &
                                                                                          & - DATA_5IM(i,j,k,l,m)
           DATA_5LM(i,j,k,l,m) = .NOT. (.FALSE. .EQV. DATA_5LM(i,j,k,l,m))
        END DO
        DATA_5LM(2,1,1,2,3) = .NOT. (.TRUE. .EQV. DATA_5LM(2,1,1,2,3))

        IF (ANY((DATA_1RB+DATA_1RM+DATA_1RD+REAL(DATA_1IM,JPRD)) /= 0.) .OR. ANY(DATA_1LM)) THEN
           CALL FIELD_ABORT("Wrong HDF5 write/read of 1D data")
        ELSE IF (ANY((DATA_2RB+DATA_2RM+DATA_2RD+REAL(DATA_2IM,JPRD)) /= 0.) .OR. ANY(DATA_2LM)) THEN
           CALL FIELD_ABORT("Wrong HDF5 write/read of 2D data")
        ELSE IF (ANY((DATA_3RB+DATA_3RM+DATA_3RD+REAL(DATA_3IM,JPRD)) /= 0.) .OR. ANY(DATA_3LM)) THEN
           CALL FIELD_ABORT("Wrong HDF5 write/read of 3D data")
        ELSE IF (ANY((DATA_4RB+DATA_4RM+DATA_4RD+REAL(DATA_4IM,JPRD)) /= 0.) .OR. ANY(DATA_4LM)) THEN
           CALL FIELD_ABORT("Wrong HDF5 write/read of 4D data")
        ELSE IF (ANY((DATA_5RB+DATA_5RM+DATA_5RD+REAL(DATA_5IM,JPRD)) /= 0.) .OR. ANY(DATA_5LM)) THEN
           CALL FIELD_ABORT("Wrong HDF5 write/read of 5D data")
        ENDIF

#if(HAVE_MPI)
        CALL MPI_FINALIZE(mpierr)
#endif

        CALL FIELD_DELETE(FIELD_DATA_1RB)
        CALL FIELD_DELETE(FIELD_DATA_1RM)
        CALL FIELD_DELETE(FIELD_DATA_1RD)
        CALL FIELD_DELETE(FIELD_DATA_1IM)
        CALL FIELD_DELETE(FIELD_DATA_1LM)

        CALL FIELD_DELETE(FIELD_DATA_2RB)
        CALL FIELD_DELETE(FIELD_DATA_2RM)
        CALL FIELD_DELETE(FIELD_DATA_2RD)
        CALL FIELD_DELETE(FIELD_DATA_2IM)
        CALL FIELD_DELETE(FIELD_DATA_2LM)

        CALL FIELD_DELETE(FIELD_DATA_3RB)
        CALL FIELD_DELETE(FIELD_DATA_3RM)
        CALL FIELD_DELETE(FIELD_DATA_3RD)
        CALL FIELD_DELETE(FIELD_DATA_3IM)
        CALL FIELD_DELETE(FIELD_DATA_3LM)

        CALL FIELD_DELETE(FIELD_DATA_4RB)
        CALL FIELD_DELETE(FIELD_DATA_4RM)
        CALL FIELD_DELETE(FIELD_DATA_4RD)
        CALL FIELD_DELETE(FIELD_DATA_4IM)
        CALL FIELD_DELETE(FIELD_DATA_4LM)

        CALL FIELD_DELETE(FIELD_DATA_5RB)
        CALL FIELD_DELETE(FIELD_DATA_5RM)
        CALL FIELD_DELETE(FIELD_DATA_5RD)
        CALL FIELD_DELETE(FIELD_DATA_5IM)
        CALL FIELD_DELETE(FIELD_DATA_5LM)
END PROGRAM
