! (C) Copyright 2022- ECMWF.
! (C) Copyright 2022- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

PROGRAM TEST_GANG

USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE PARKIND1
USE OMP_LIB, ONLY: OMP_GET_MAX_THREADS
IMPLICIT NONE

CLASS(FIELD_4RD), POINTER :: YLF4
TYPE(FIELD_3RD_PTR), ALLOCATABLE :: YLF3L (:)

REAL (KIND=JPRD), POINTER :: ZHST4 (:,:,:,:), ZDEV4 (:,:,:,:)
REAL (KIND=JPRD), POINTER :: ZHST3 (:,:,:), ZDEV3 (:,:,:)

INTEGER (KIND=JPIM), PARAMETER :: NPROMA = 32, NFLEVG = 15, NDIM = 3, NGPBLKS = 10
INTEGER (KIND=JPIM) :: JLON, JLEV, JFLD, JBLK
INTEGER (KIND=JPIM) :: JDIM
LOGICAL, PARAMETER :: LLPERSISTENT = .TRUE.

INTEGER (KIND=JPIM), PARAMETER :: ILB (4) = [1,0,1,1], IUB (4) = [NPROMA, NFLEVG, NDIM, NGPBLKS]

#include "abor1.intfb.h"

REAL (KIND=JPRB) :: FUNC
FUNC (JLON, JLEV, JFLD, JBLK) = REAL (JLON, JPRD) + 100._JPRD * (REAL (JLEV, JPRD) + 100._JPRD * &
                             & (REAL (JFLD, JPRD) + 100._JPRD * REAL (JBLK, JPRD)))

CALL NEW_YLF4
CALL SET_HOST_YLF4
CALL GET_DEVICE_YLF4
CALL GET_DEVICE_YLF3
CALL DEL_YLF4

CONTAINS

SUBROUTINE NEW_YLF4


WRITE (0, *) __FILE__, ':', __LINE__ 

CALL FIELD_NEW (YLF4, CHILDREN=YLF3L, UBOUNDS=IUB, LBOUNDS=ILB, PERSISTENT=LLPERSISTENT)

CALL YLF4%SET_STATUS (0)

STOP

CALL CHECK_STATUS

WRITE (0, *) __FILE__, ':', __LINE__ 

END SUBROUTINE

SUBROUTINE SET_HOST_YLF4

WRITE (0, *) __FILE__, ':', __LINE__

ZHST4 => GET_HOST_DATA_RDWR (YLF4)

CALL CHECK_STATUS

WRITE (0, *) __FILE__, ':', __LINE__

DO JBLK = 1, NGPBLKS
  DO JFLD = 1, NDIM
    DO JLEV = 0, NFLEVG
      DO JLON = 1, NPROMA
        ZHST4 (JLON, JLEV, JFLD, JBLK) = FUNC (JLON, JLEV, JFLD, JBLK)
      ENDDO
    ENDDO
  ENDDO
ENDDO

CALL CHECK_STATUS

END SUBROUTINE

SUBROUTINE DEL_YLF4

DEALLOCATE (YLF3L)
CALL FIELD_DELETE (YLF4)

END SUBROUTINE

SUBROUTINE GET_DEVICE_YLF4

IF (SIZE (YLF3L) /= NDIM) CALL ABOR1 ('SIZE MISMATCH')

ZDEV4 => GET_DEVICE_DATA_RDONLY (YLF4)

CALL CHECK_DIMS_YLF4 (ZDEV4)

!$acc serial present (ZDEV4) 

DO JBLK = 1, NGPBLKS
  DO JFLD = 1, NDIM
    DO JLEV = 0, NFLEVG
      DO JLON = 1, NPROMA
        IF (ZDEV4 (JLON, JLEV, JFLD, JBLK) /= FUNC (JLON, JLEV, JFLD, JBLK)) THEN
          PRINT *, ZDEV4 (JLON, JLEV, JFLD, JBLK)
          PRINT *,  FUNC (JLON, JLEV, JFLD, JBLK)
          STOP 1
        ENDIF
      ENDDO
    ENDDO
  ENDDO
ENDDO

!$acc end serial

CALL CHECK_STATUS

END SUBROUTINE

SUBROUTINE CHECK_DIMS_YLF4 (P4)

REAL (KIND=JPRD), POINTER :: P4 (:,:,:,:)

DO JDIM = 1, 4
  IF (LBOUND (P4, JDIM) /= ILB (JDIM)) THEN
    PRINT *, LBOUND (P4) 
    PRINT *, ILB 
    CALL ABOR1 ('LBOUND MISMATCH')
  ENDIF
  IF (UBOUND (P4, JDIM) /= IUB (JDIM)) THEN
    PRINT *, UBOUND (P4)  
    PRINT *, IUB 
    CALL ABOR1 ('UBOUND MISMATCH')
  ENDIF
ENDDO

END SUBROUTINE

SUBROUTINE CHECK_DIMS_YLF3 (P3)

REAL (KIND=JPRD), POINTER :: P3 (:,:,:)

DO JDIM = 1, 2
  IF (LBOUND (P3, JDIM) /= ILB (JDIM)) CALL ABOR1 ('LBOUND MISMATCH')
  IF (UBOUND (P3, JDIM) /= IUB (JDIM)) CALL ABOR1 ('UBOUND MISMATCH')
ENDDO

IF (LBOUND (P3, 3) /= ILB (4)) CALL ABOR1 ('LBOUND MISMATCH')
IF (UBOUND (P3, 3) /= IUB (4)) CALL ABOR1 ('UBOUND MISMATCH')

END SUBROUTINE

SUBROUTINE GET_DEVICE_YLF3

DO JFLD = 1, NDIM

  ZDEV3 => GET_DEVICE_DATA_RDONLY (YLF3L (JFLD)%PTR)

  CALL CHECK_DIMS_YLF3 (ZDEV3)

!$acc serial present (ZDEV3) copyin (JFLD)

  DO JBLK = 1, NGPBLKS
    DO JLEV = 0, NFLEVG
      DO JLON = 1, NPROMA
        IF (ZDEV3 (JLON, JLEV, JBLK) /= FUNC (JLON, JLEV, JFLD, JBLK)) THEN
          PRINT *, ZDEV3 (JLON, JLEV, JBLK)
          PRINT *,  FUNC (JLON, JLEV, JFLD, JBLK)
          STOP 1
        ENDIF
      ENDDO
    ENDDO
  ENDDO

!$acc end serial

  CALL CHECK_STATUS

ENDDO


END SUBROUTINE

SUBROUTINE CHECK_STATUS

DO JFLD = 1, NDIM
  IF (YLF4%ISTATUS /= YLF3L(JFLD)%PTR%ISTATUS) THEN
    PRINT *, JFLD
    WRITE (*, '("YLF4 = ",Z16.16)') YLF4%ISTATUS
    WRITE (*, '("YLF3L (",I0,")=",Z16.16)') JFLD, YLF3L(JFLD)%PTR%ISTATUS
    CALL ABOR1 ('STATUS MISMATCH')
  ENDIF
ENDDO

END SUBROUTINE

END PROGRAM 
