! (C) Copyright 2022- ECMWF.
! (C) Copyright 2022- Meteo-France.
! (C) Copyright 2023- NVIDIA
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

PROGRAM TEST_STATISTICS

USE FIELD_ABORT_MODULE
USE FIELD_STATISTICS_MODULE
USE FIELD_MODULE
USE PARKIND1
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE

IMPLICIT NONE
CLASS(FIELD_4IM), POINTER :: YLF1 => NULL(), YLF2 => NULL ()
INTEGER (KIND=JPIM) :: UBOUNDS (4) = [4,4,2,7]
INTEGER (KIND=JPIM) :: IDATA0 (5,3,2,9)
INTEGER (KIND=JPIM), POINTER :: IDATA (:,:,:,:)

#define assert(cond) IF (.NOT.(cond)) CALL FIELD_ABORT ("'"//#cond//"' IS FALSE")

FIELD_STATISTICS_ENABLE = .TRUE.

CALL FIELD_NEW (YLF1, UBOUNDS=UBOUNDS, PERSISTENT=.TRUE.)

assert (FIELD_STATISTICS%NFIELDS_CUR==1)

CALL FIELD_NEW (YLF2, DATA=IDATA0, PERSISTENT=.TRUE.)

assert (FIELD_STATISTICS%NFIELDS_CUR==2)

assert (FIELD_STATISTICS%MEMORY_DEVICE_CUR==0)

IDATA => GET_DEVICE_DATA_RDONLY (YLF1)

assert (FIELD_STATISTICS%MEMORY_DEVICE_CUR==KIND(IDATA)*SIZE(IDATA))

IDATA => GET_DEVICE_DATA_RDONLY (YLF2)

assert (FIELD_STATISTICS%MEMORY_DEVICE_CUR==JPIM*PRODUCT(UBOUNDS)+JPIM*SIZE(IDATA0))

CALL FIELD_DELETE (YLF1)

assert (FIELD_STATISTICS%NFIELDS_CUR==1)

CALL FIELD_DELETE (YLF2)

assert (FIELD_STATISTICS%NFIELDS_CUR==0)

assert (FIELD_STATISTICS%NFIELDS_MAX==2)

assert (FIELD_STATISTICS%MEMORY_DEVICE_CUR==0)

assert (FIELD_STATISTICS%MEMORY_DEVICE_MAX==PRODUCT(UBOUNDS)*JPIM+SIZE(IDATA0)*JPIM)

END PROGRAM 
