MODULE FIELD_STATISTICS_MODULE

USE PARKIND1, ONLY : JPIB, JPIM

IMPLICIT NONE

TYPE FIELD_STATISTICS_TYPE
  INTEGER (KIND=JPIB) :: MEMORY_HOST_CUR = 0
  INTEGER (KIND=JPIB) :: MEMORY_HOST_MAX = 0

  INTEGER (KIND=JPIB) :: MEMORY_DEVICE_CUR = 0
  INTEGER (KIND=JPIB) :: MEMORY_DEVICE_MAX = 0

  INTEGER (KIND=JPIB) :: NFIELDS_CUR = 0
  INTEGER (KIND=JPIB) :: NFIELDS_MAX = 0
END TYPE

LOGICAL, SAVE :: FIELD_STATISTICS_ENABLE = .FALSE.
TYPE (FIELD_STATISTICS_TYPE), SAVE :: FIELD_STATISTICS

CONTAINS

SUBROUTINE FIELD_STATISTICS_NEW () 

FIELD_STATISTICS%NFIELDS_CUR = FIELD_STATISTICS%NFIELDS_CUR+1
FIELD_STATISTICS%NFIELDS_MAX = MAX(FIELD_STATISTICS%NFIELDS_CUR,FIELD_STATISTICS%NFIELDS_MAX)

END SUBROUTINE 

SUBROUTINE FIELD_STATISTICS_DELETE () 

FIELD_STATISTICS%NFIELDS_CUR = FIELD_STATISTICS%NFIELDS_CUR-1

END SUBROUTINE 

SUBROUTINE FIELD_STATISTICS_HOST_ALLOCATE (KSIZE) 

INTEGER (KIND=JPIB), INTENT (IN) :: KSIZE

FIELD_STATISTICS%MEMORY_HOST_CUR = FIELD_STATISTICS%MEMORY_HOST_CUR+KSIZE
FIELD_STATISTICS%MEMORY_HOST_MAX = MAX(FIELD_STATISTICS%MEMORY_HOST_CUR,FIELD_STATISTICS%MEMORY_HOST_MAX)

END SUBROUTINE 

SUBROUTINE FIELD_STATISTICS_HOST_DEALLOCATE (KSIZE) 

INTEGER (KIND=JPIB), INTENT (IN) :: KSIZE

FIELD_STATISTICS%MEMORY_HOST_CUR = FIELD_STATISTICS%MEMORY_HOST_CUR-KSIZE

END SUBROUTINE 

SUBROUTINE FIELD_STATISTICS_DEVICE_ALLOCATE (KSIZE) 

INTEGER (KIND=JPIB), INTENT (IN) :: KSIZE

FIELD_STATISTICS%MEMORY_DEVICE_CUR = FIELD_STATISTICS%MEMORY_DEVICE_CUR+KSIZE
FIELD_STATISTICS%MEMORY_DEVICE_MAX = MAX(FIELD_STATISTICS%MEMORY_DEVICE_CUR,FIELD_STATISTICS%MEMORY_DEVICE_MAX)

END SUBROUTINE 

SUBROUTINE FIELD_STATISTICS_DEVICE_DEALLOCATE (KSIZE) 

INTEGER (KIND=JPIB), INTENT (IN) :: KSIZE

FIELD_STATISTICS%MEMORY_DEVICE_CUR = FIELD_STATISTICS%MEMORY_DEVICE_CUR-KSIZE

END SUBROUTINE 

END MODULE
