! (C) Copyright 2022- ECMWF.
! (C) Copyright 2022- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE HDF5_COMMON_MODULE

USE HDF5, ONLY: H5open_F, H5Fopen_F, H5Fcreate_F, H5Dclose_F, H5Sclose_F, H5Fclose_F, H5close_F
USE HDF5, ONLY: HID_T, H5F_ACC_RDWR_F,  H5F_ACC_TRUNC_F
USE FIELD_ABORT_MODULE, ONLY: FIELD_ABORT

IMPLICIT NONE

CONTAINS

SUBROUTINE INIT_HDF5_STORAGE()

  INTEGER :: HDFERR

  CALL H5open_F(HDFERR)
  IF (HDFERR /= 0) CALL FIELD_ABORT("Unable to initialize HDF5.")

END SUBROUTINE INIT_HDF5_STORAGE

SUBROUTINE OPEN_HDF5_STORAGE(FILENAME, FILE_ID)

  CHARACTER(LEN=*), INTENT(IN)  :: FILENAME
  INTEGER(HID_T)  , INTENT(OUT) :: FILE_ID
  INTEGER :: HDFERR
  LOGICAL :: HDF5_FILE_EXISTS, HDF5_DATASET_EXISTS 

  INQUIRE(FILE=TRIM(FILENAME), EXIST=HDF5_FILE_EXISTS)
  IF (HDF5_FILE_EXISTS) THEN
      CALL H5Fopen_F(  TRIM(FILENAME), H5F_ACC_RDWR_F , FILE_ID, HDFERR)
      IF (HDFERR /= 0) CALL FIELD_ABORT("Unable to open file: "//TRIM(FILENAME)//". Inquire says: file EXISTS")
  ELSE
      CALL H5Fcreate_F(TRIM(FILENAME), H5F_ACC_TRUNC_F, FILE_ID, HDFERR)
      IF (HDFERR /= 0) CALL FIELD_ABORT("Unable to create file: "//TRIM(FILENAME))   
  END IF

END SUBROUTINE OPEN_HDF5_STORAGE

SUBROUTINE CLOSE_HDF5_STORAGE(DSET_ID, SPACE_ID, FILE_ID)

  INTEGER(HID_T) :: FILE_ID, SPACE_ID
  INTEGER(HID_T) :: DSET_ID
  INTEGER :: HDFERR

  CALL H5Dclose_F( DSET_ID, HDFERR)
  IF (HDFERR /= 0) CALL FIELD_ABORT("Unable to close HDF5 dataset.")
  CALL H5Sclose_F(SPACE_ID, HDFERR)
  IF (HDFERR /= 0) CALL FIELD_ABORT("Unable to close HDF5 space.")
  CALL H5Fclose_F( FILE_ID, HDFERR)
  IF (HDFERR /= 0) CALL FIELD_ABORT("Unable to close HDF5 file.")

END SUBROUTINE CLOSE_HDF5_STORAGE

SUBROUTINE FINALIZE_HDF5_STORAGE()

  INTEGER :: HDFERR

  CALL H5close_F( HDFERR)
  IF (HDFERR /= 0) CALL FIELD_ABORT("Unable to finalize HDF5.")

END SUBROUTINE FINALIZE_HDF5_STORAGE

SUBROUTINE NAME_HDF5_STORAGE(FILENAME,FNAME_WITH_RANK)
USE MPL_MODULE, ONLY: MPL_RANK, MPL_NUMPROC
USE FIELD_ABORT_MODULE, ONLY: FIELD_ABORT
USE MPI
CHARACTER(LEN=*),              INTENT(IN)  :: FILENAME
CHARACTER(LEN=:), ALLOCATABLE, INTENT(OUT) :: FNAME_WITH_RANK
CHARACTER(LEN=:), ALLOCATABLE :: RANK_STR
INTEGER :: NAME_LEN, RANK_LEN
integer rank,ierr
RANK_LEN = CEILING(LOG10(REAL(ABS(MPL_RANK)+1)))  
ALLOCATE(CHARACTER(RANK_LEN) :: RANK_STR)
CALL MPI_COMM_RANK(MPI_COMM_WORLD,rank,ierr)
PRINT *,"Rank is",MPL_RANK, rank
CALL FIELD_ABORT("From NAME_HDF5_STORAGE:single rank") 
IF(MPL_NUMPROC > 1) THEN
1004 format(1x,'Rank from MPL is',i0)
    write(0,1004) MPL_RANK
   WRITE(RANK_STR, '(I0)') MPL_RANK
   NAME_LEN = LEN_TRIM(FILENAME) + LEN("_rank") + LEN_TRIM(RANK_STR) + LEN(".hdf5")
   ALLOCATE(CHARACTER(LEN=NAME_LEN) :: FNAME_WITH_RANK)
   FNAME_WITH_RANK = TRIM(FILENAME) // "_rank" // TRIM(RANK_STR) // ".hdf5"
ELSE
   NAME_LEN = LEN_TRIM(FILENAME) + LEN(".hdf5")
   ALLOCATE(CHARACTER(LEN=NAME_LEN) :: FNAME_WITH_RANK)
   FNAME_WITH_RANK = TRIM(FILENAME) // ".hdf5"
ENDIF
END SUBROUTINE NAME_HDF5_STORAGE

END MODULE HDF5_COMMON_MODULE
