name: build-hpc

# Controls when the action will run
on:

  # Trigger the workflow on all pushes to main, except on tag creation
  push:
    branches:
    - main
    tags-ignore:
    - '**'

  # Trigger the workflow on all pull requests
  pull_request: ~

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

  # Trigger after public PR approved for CI
  pull_request_target:
    types: [labeled]

env:
    sbatch_options_gpu: |
              #SBATCH --time=00:20:00
              #SBATCH --nodes=1
              #SBATCH --ntasks=2
              #SBATCH --cpus-per-task=32
              #SBATCH --gpus-per-task=1
              #SBATCH --mem=100G
              #SBATCH --qos=dg
    sbatch_options_cpu: |
              #SBATCH --time=00:20:00
              #SBATCH --nodes=1
              #SBATCH --ntasks=2
              #SBATCH --cpus-per-task=32
              #SBATCH --hint=nomultithread
              #SBATCH --qos=np
    module_list_nvhpc:
              - cmake
              - ninja
              - ecbuild
              - prgenv/nvidia
              - nvidia/24.5
              - hpcx-openmpi/2.19.0-cuda
              - hdf5/1.14.3
              - python3
    module_list_gnu:
              - cmake
              - ninja
              - ecbuild
              - prgenv/gnu
              - gcc/14.2.0
              - openmpi/4.1.1.1
              - hdf5/1.14.3
              - python3
    module_list_intel:
              - cmake
              - ninja
              - ecbuild
              - prgenv/intel
              - intel/2023.2.0
              - hpcx-openmpi/2.9.0
              - hdf5/1.14.3
              - python3
jobs:
  ci-hpc:
    name: ci-hpc
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}

    strategy:
      fail-fast: false    # false: try to complete all jobs

      matrix:
        build_type: [RelWithDebInfo]
              site: ac-batch

        include:

      # CPU builds
      - name: "ac-cpu intel"
        compiler: intel-classic
        cuda: False
        openmp: False
        module: ${module_list_intel}
        sbatch_options: ${sbatch_options_cpu}

      - name: "ac-cpu gnu"
        compiler: gnu-14
        cuda: False
        openmp: False
        module: ${module_list_gnu}
        sbatch_options: ${sbatch_options_cpu}
        
      # GPU builds with different combinations
      - name: "ac-gpu nvhpc OpenACC + CUDA"
        cuda: True
        module: ${module_list_nvhpc}
        sbatch_options: ${sbatch_options_gpu}

      - name: "ac-gpu nvhpc OMP offload"
        cuda: False
        openmp: True
        module: ${module_list_nvhpc}
        sbatch_options: ${sbatch_options_gpu}
 
      - name: "ac-gpu nvhpc OMP offload + CUDA"
        cuda: True
        openmp: True
        module: ${module_list_nvhpc}
        sbatch_options: ${sbatch_options_gpu}

      - name: "ac-gpu nvhpc OpenACC"
        cuda: False
        openmp: False
        module: ${module_list_nvhpc}
        sbatch_options: ${sbatch_options_gpu}

    runs-on: [self-hosted, linux, hpc]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: ecmwf-actions/reusable-workflows/ci-hpc-generic@v2
        with:
          site: ${{ matrix.site }}
          troika_user: ${{ secrets.HPC_CI_SSH_USER }}
          sbatch_options: ${{ matrix.sbatch_options }}
          template_data: |
            cmake_options:
              - -DENABLE_OMP_OFFLOAD=${{ matrix.openmp }}
              - -DENABLE_CUDA=${{ matrix.cuda }}
              - -DENABLE_IO_SERIAL=ON
              - -DENABLE_SINGLE_PRECISION=ON
              - -DENABLE_DOUBLE_PRECISION=ON
              - -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            dependencies:
              ecmwf/fckit:
                version: 0.14.0
                cmake_options:
                  - -DENABLE_TESTS=OFF
                  - -DENABLE_FCKIT_VENV=ON
                  - -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
              ecmwf-ifs/fiat:
                version: 1.6.1
                cmake_options:
                  - -DENABLE_TESTS=OFF
                  - -DENABLE_SINGLE_PRECISION=ON
                  - -DENABLE_DOUBLE_PRECISION=ON
                  - -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          template: |
            {% for module in "${{ join(matrix.modules, ',') }}".split(',') %}
              module load {{module}}
            {% endfor %}
            BASEDIR=$PWD
            {% for name, options in dependencies.items() %}
                mkdir -p {{name}}
                pushd {{name}}
                git init
                git remote add origin ${{ github.server_url }}/{{name}}
                git fetch origin {{options['version']}}
                git reset --hard FETCH_HEAD
                cmake -G Ninja -S . -B build \
                  {% for name in dependencies %}
                    {% set org, proj = name.split('/') %}
                    -D{{proj}}_ROOT=$BASEDIR/{{name}}/installation \
                  {% endfor %}
                  {{ options['cmake_options']|join(' ') }}
                cmake --build build
                cmake --install build --prefix installation
                popd
            {% endfor %}
            REPO=${{ github.event.pull_request.head.repo.full_name || github.repository }}
            SHA=${{ github.event.pull_request.head.sha || github.sha }}
            mkdir -p $REPO
            pushd $REPO
            git init
            git remote add origin ${{ github.server_url }}/$REPO
            git fetch origin $SHA
            git reset --hard FETCH_HEAD
            popd
            cmake -G Ninja -S $REPO -B build \
              {% for name in dependencies %}
                {% set org, proj = name.split('/') %}
                -D{{proj}}_ROOT=$BASEDIR/{{name}}/installation \
              {% endfor %}
              {{ cmake_options|join(' ') }}
            cmake --build build
            ctest --test-dir build --output-on-failure

